# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctas_ahorros_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA_AHO_EST_HIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('est_cta_ant', models.CharField(choices=[('P', 'Por Aplicar'), ('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1)),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro')),
            ],
            options={
                'db_table': 'cta_aho_est_his',
                'unique_together': {('cta_aho', 'fecha')},
            },
        ),
    ]
