# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctas_ahorros_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA_AHO_EST_HIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('est_cta_ant', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1)),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro')),
            ],
            options={
                'db_table': 'cta_aho_est_his',
                'unique_together': {('cta_aho', 'fecha')},
            },
        ),
    ]
