# Generated by Django 4.2.4 on 2024-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_ctas_ahorros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta_aho_est_his',
            name='est_cta_ant',
            field=models.CharField(choices=[('P', 'Por Aplicar'), ('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1),
        ),
    ]
