# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_economico_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVOS_FIJOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, verbose_name='Codigo del Elemento')),
                ('descripcion', models.CharField(max_length=128, verbose_name='Descripcion del Elemento')),
                ('fecha_de_alta', models.DateField(null=True, verbose_name='Fecha de alta del Elemento')),
                ('valor_elem', models.FloatField(null=True)),
                ('meses_dep', models.IntegerField(null=True)),
                ('valor_salva', models.FloatField(null=True)),
                ('dep_acu_vig_ant', models.FloatField(null=True)),
                ('det_acu_vig_ant', models.FloatField(null=True)),
                ('val_acu_vig_ant', models.FloatField(null=True)),
                ('cod_cta_dep', models.CharField(max_length=10, null=True, verbose_name='Cuenta Depreciación')),
                ('cod_cta_dep_gas', models.CharField(max_length=10, null=True, verbose_name='Cta Dep Gasto')),
                ('cod_cta_det', models.CharField(max_length=10, null=True, verbose_name='Cta Deterioro')),
                ('cod_cta_det_gas', models.CharField(max_length=10, null=True, verbose_name='Cta Deterioro Gasto')),
                ('de_baja', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Está de Baja?')),
                ('deta_eco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detalle_economico_app.detalle_econo', verbose_name='Asiento de Alta')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'activos_fijos',
                'indexes': [models.Index(fields=['oficina', 'descripcion'], name='activos_fij_oficina_2ade86_idx')],
                'unique_together': {('oficina', 'codigo')},
            },
        ),
    ]
