# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas_ahorro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMP_CON_LIN_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_imp', models.CharField(max_length=2, null=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, null=True, verbose_name='Descripción')),
                ('ctaafeact', models.CharField(max_length=10, null=True, verbose_name='Cuenta Activa')),
                ('ctaafeina', models.CharField(max_length=10, null=True, verbose_name='Cuenta Inactiva')),
                ('ctaafeint', models.CharField(max_length=10, null=True, verbose_name='Cuenta Intereses')),
                ('ctaretfue', models.CharField(max_length=10, null=True, verbose_name='Cuenta Retefuente')),
                ('linea_ahorro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lineas_ahorro_app.lineas_ahorro', verbose_name='Línea de Ahorro')),
            ],
            options={
                'db_table': 'imp_con_lin_aho',
                'unique_together': {('linea_ahorro', 'cod_imp')},
            },
        ),
    ]
