# Generated by Django 4.2.4 on 2025-02-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte_cat_his',
            old_name='pro_ind',
            new_name='pro_ind_int',
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='pro_ind_kap',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
