# Generated by Django 4.2.4 on 2025-02-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0002_rename_pro_ind_carte_cat_his_pro_ind_int_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte_cat_his',
            old_name='ali_cuota',
            new_name='ali_acu',
        ),
        migrations.RenameField(
            model_name='carte_cat_his',
            old_name='conta_per',
            new_name='conta_ali',
        ),
    ]
