# Generated by Django 4.2.4 on 2025-02-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0003_rename_ali_cuota_carte_cat_his_ali_acu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte_cat_his',
            old_name='conta_ali',
            new_name='conta_per',
        ),
    ]
