# Generated by Django 4.2.4 on 2025-02-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0004_rename_conta_ali_carte_cat_his_conta_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte_cat_his',
            old_name='conta_per',
            new_name='conta_ali',
        ),
    ]
