# Generated by Django 4.2.4 on 2025-02-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0005_rename_conta_per_carte_cat_his_conta_ali'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carte_cat_his',
            index=models.Index(fields=['oficina', 'nit', 'fecha'], name='carte_cat_h_oficina_1e108f_idx'),
        ),
    ]
