# Generated by Django 4.2.4 on 2025-03-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0007_remove_carte_cat_his_ali_acu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte_cat_his',
            name='ali_acu',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='aporte',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='castigo',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='cat_arr',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='cat_eva',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='cat_int_mes',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='cat_mod',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='cat_mor',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='cat_ree',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='cat_sel',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='categoria',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='conta_ali',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='gas_pro_gen',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='gas_pro_ind',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='int_conkas_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='pdi',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='per_esp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='pro_inc',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='pro_ind_int',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='pro_ind_kap',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='puntaje',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='sal_cap_pe',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='sal_cat_int',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='sal_int_contin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='sal_int_pe',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='saldo_1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='saldo_2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='val_gar_hip',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='vea',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='carte_cat_his',
            name='zeta',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
