# Generated by Django 4.2.4 on 2025-03-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0008_carte_cat_his_ali_acu_carte_cat_his_aporte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte_cat_his',
            old_name='gas_pro_ind',
            new_name='gas_pro_ind_acu',
        ),
    ]
