# Generated by Django 4.2.4 on 2025-03-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0009_rename_gas_pro_ind_carte_cat_his_gas_pro_ind_acu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pe_carte_his',
            name='val_mora315',
            field=models.SmallIntegerField(default=0),
        ),
    ]
