# Generated by Django 4.2.4 on 2025-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0011_remove_pe_carte_his_val_amor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pe_mode_refe',
            name='coe_mora315',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
