# Generated by Django 4.2.4 on 2025-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0012_pe_mode_refe_coe_mora315'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte_cat_his',
            name='cla_gar',
            field=models.CharField(default='  ', max_length=2, null=True),
        ),
    ]
