# Generated by Django 4.2.4 on 2025-04-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recla_carte_app', '0013_carte_cat_his_cla_gar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CATE_INTE',
        ),
    ]
