# Generated by Django 4.2.4 on 2025-04-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas_app', '0001_initial'),
        ('recla_carte_app', '0014_delete_cate_inte'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPKI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cod_cre', models.CharField(max_length=10, null=True)),
                ('tipo', models.CharField(max_length=1, null=True)),
                ('nit', models.CharField(max_length=12, null=True)),
                ('fec_des', models.DateField(blank=True, null=True)),
                ('cod_imp', models.CharField(max_length=2, null=True)),
                ('cat_ini', models.CharField(default=' ', max_length=1, null=True)),
                ('cat_fin', models.CharField(default=' ', max_length=1, null=True)),
                ('sal_cap_ini', models.FloatField(blank=True, default=0.0)),
                ('sal_cap_fin', models.FloatField(blank=True, default=0.0)),
                ('int_dia_ini', models.FloatField(blank=True, default=0.0)),
                ('int_cau_ini', models.FloatField(blank=True, default=0.0)),
                ('inicio', models.FloatField(blank=True, default=0.0)),
                ('int_pag', models.FloatField(blank=True, default=0.0)),
                ('int_dia_fin', models.FloatField(blank=True, default=0.0)),
                ('int_cau_fin', models.FloatField(blank=True, default=0.0)),
                ('final', models.FloatField(blank=True, default=0.0)),
                ('int_cau_mes', models.FloatField(blank=True, default=0.0)),
                ('int_pag_ant', models.FloatField(blank=True, default=0.0)),
                ('int_pag_act', models.FloatField(blank=True, default=0.0)),
                ('int_pag_ade', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_A', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_B', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_C', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_D', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_E', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_Z', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_ZC', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_ZD', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_ZE', models.FloatField(blank=True, default=0.0)),
                ('ip_ant_ZF', models.FloatField(blank=True, default=0.0)),
                ('cue_pr_cob_A', models.FloatField(blank=True, default=0.0)),
                ('cue_pr_cob_B', models.FloatField(blank=True, default=0.0)),
                ('cue_pr_cob_C', models.FloatField(blank=True, default=0.0)),
                ('cue_pr_cob_D', models.FloatField(blank=True, default=0.0)),
                ('cue_pr_cob_E', models.FloatField(blank=True, default=0.0)),
                ('cue_pr_cob_F', models.FloatField(blank=True, default=0.0)),
                ('cau_ZC', models.FloatField(blank=True, default=0.0)),
                ('cau_ZD', models.FloatField(blank=True, default=0.0)),
                ('cau_ZE', models.FloatField(blank=True, default=0.0)),
                ('cau_ZF', models.FloatField(blank=True, default=0.0)),
                ('cau_ZET', models.FloatField(blank=True, default=0.0)),
                ('ingreso', models.FloatField(blank=True, default=0.0)),
                ('cue_por_pag', models.FloatField(blank=True, default=0.0)),
                ('cre_con_cas', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default=' ', max_length=1)),
                ('int_con', models.FloatField(blank=True, default=0.0)),
                ('pro_ind_ini', models.FloatField(blank=True, default=0.0)),
                ('pro_ind_fin', models.FloatField(blank=True, default=0.0)),
                ('gas_pro_ind_ini', models.FloatField(blank=True, default=0.0, null=True)),
                ('gas_pro_ind_fin', models.FloatField(blank=True, default=0.0)),
                ('pro_gen_ini', models.FloatField(blank=True, default=0.0)),
                ('pro_gen_fin', models.FloatField(blank=True, default=0.0)),
                ('gas_gen_ini', models.FloatField(blank=True, default=0.0)),
                ('gas_gen_fin', models.FloatField(blank=True, default=0.0)),
                ('det_ind_gas_acu', models.FloatField(blank=True, default=0.0)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas')),
            ],
            options={
                'db_table': 'RPKI',
                'unique_together': {('oficina', 'fecha', 'cod_cre')},
            },
        ),
    ]
