# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilizacion_lineas_ahorros_app', '0001_initial'),
        ('ctas_ahorros_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA_CDAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampliacion', models.IntegerField(verbose_name='Ampliación')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('plazo_mes', models.IntegerField(blank=True, null=True, verbose_name='Plazo en Meses')),
                ('tiae', models.FloatField(blank=True, null=True, verbose_name='Tasa Anual Efect.')),
                ('Periodicidad', models.IntegerField(blank=True, null=True, verbose_name='Nro de Pagos de Interes')),
                ('cta_int_ret', models.CharField(max_length=10, null=True, verbose_name='Cuenta Contable Intereses')),
                ('aplicado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Aplicado?')),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro')),
                ('imp_con', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilizacion_lineas_ahorros_app.imp_con_lin_aho', verbose_name='Imp_contable')),
            ],
            options={
                'db_table': 'cta_cdat',
                'unique_together': {('cta_aho', 'ampliacion')},
            },
        ),
    ]
