# Generated by Django 4.2.4 on 2024-09-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilizacion_lineas_ahorros_app', '0001_initial'),
        ('cdat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta_cdat',
            name='imp_con',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilizacion_lineas_ahorros_app.imp_con_lin_aho', verbose_name='Imp_contable'),
        ),
    ]
