# Generated by Django 4.2.4 on 2024-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdat_app', '0002_cta_cdat_imp_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta_cdat',
            name='Periodicidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro de Pagos de Interes'),
        ),
    ]
