# Generated by Django 4.2.4 on 2024-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdat_app', '0002_cta_cdat_imp_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta_cdat',
            name='Periodicidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nro de Pagos de Interes'),
        ),
        migrations.AlterField(
            model_name='cta_cdat',
            name='tiae',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa Anual Efect.'),
        ),
    ]
