# Generated by Django 4.2.4 on 2024-10-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdat_app', '0003_alter_cta_cdat_periodicidad'),
        ('cdat_app', '0003_alter_cta_cdat_periodicidad_alter_cta_cdat_tiae'),
    ]

    operations = [
    ]
