# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_producto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMBIOS_CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_cam', models.CharField(choices=[('2', 'Ajuste Pag Ant'), ('3', 'Ajuste otros'), ('4', 'Castigo/Condonación')], max_length=1, null=True, verbose_name='Tipo de Cambio?')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('capital', models.FloatField(blank=True, null=True, verbose_name='Capital')),
                ('int_cor', models.FloatField(blank=True, null=True, verbose_name='Interés Corriente')),
                ('int_mor', models.FloatField(blank=True, null=True, verbose_name='Interés de Mora')),
                ('pol_seg', models.FloatField(blank=True, null=True, verbose_name='Póliza')),
                ('des_pp', models.FloatField(blank=True, null=True, verbose_name='Descuento Pronto Pago')),
                ('acreedor', models.FloatField(blank=True, null=True, verbose_name='Acreedor')),
                ('det_pro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Detalle Producto')),
            ],
            options={
                'db_table': 'cambios_cre',
                'indexes': [models.Index(fields=['det_pro', 'tip_cam'], name='cambios_cre_det_pro_5c73de_idx')],
                'unique_together': {('det_pro', 'tip_cam')},
            },
        ),
    ]
