# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_producto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMBIOS_CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_cam', models.CharField(choices=[('2', 'Ajuste'), ('3', 'Descuento Pronto Pago'), ('4', 'Castigo/Condonación')], max_length=1, null=True, verbose_name='Tipo de Cambio?')),
                ('capital', models.FloatField(blank=True, null=True, verbose_name='Capital')),
                ('int_cor', models.FloatField(blank=True, null=True, verbose_name='Interés Corriente')),
                ('int_mor', models.FloatField(blank=True, null=True, verbose_name='Interés de Mora')),
                ('pol_seg', models.FloatField(blank=True, null=True, verbose_name='Póliza')),
                ('des_pp', models.FloatField(blank=True, null=True, verbose_name='Descuento Pronto Pago')),
                ('acreedor', models.FloatField(blank=True, null=True, verbose_name='Acreedor')),
                ('det_pro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Detalle Producto')),
            ],
            options={
                'db_table': 'cambios_cre',
                'unique_together': {('det_pro', 'tip_cam')},
            },
        ),
    ]
