# Generated by Django 4.2.4 on 2024-06-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_cre',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
