# Generated by Django 4.2.4 on 2024-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios_creditos_app', '0002_cambios_cre_fecha'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cambios_cre',
            index=models.Index(fields=['det_pro', 'tip_cam'], name='cambios_cre_det_pro_5c73de_idx'),
        ),
    ]
