# Generated by Django 4.2.4 on 2025-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios_creditos_app', '0003_cambios_cre_cambios_cre_det_pro_5c73de_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios_cre',
            name='tip_cam',
            field=models.CharField(choices=[('2', 'Ajuste Pag Ant'), ('3', 'Ajuste otros'), ('4', 'Castigo/Condonación')], max_length=1, null=True, verbose_name='Tipo de Cambio?'),
        ),
    ]
