# Generated by Django 4.2.4 on 2024-10-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0001_initial'),
        ('terceros_app', '0002_alter_terceros_celular1_alter_terceros_celular2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAJEROS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha Ingreso Cajero')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro Cajero')),
                ('activo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Está Activo?')),
                ('cta_con_caja', models.CharField(max_length=10, verbose_name='Cta Contable caja')),
                ('cta_con_acre', models.CharField(max_length=10, verbose_name='Cta Contable Acreedores')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
                ('tercero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Tercero')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cajeros',
                'unique_together': {('user', 'oficina')},
            },
        ),
    ]
