# Generated by Django 4.2.4 on 2024-12-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0004_alter_terceros_tip_ter'),
        ('cajeros_app', '0003_alter_cajeros_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajeros',
            name='tercero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terceros_app.terceros', verbose_name='Tercero'),
        ),
    ]
