# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIERRE_MES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('protegido', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Protegido?')),
                ('tot_deb', models.FloatField(blank=True, null=True, verbose_name='Total Débito')),
                ('tot_cre', models.FloatField(blank=True, null=True, verbose_name='Total Crédito')),
                ('fec_cie', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('usuario', models.CharField(max_length=16, verbose_name='Usuario')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'cierre_mes',
                'unique_together': {('oficina', 'fecha')},
            },
        ),
    ]
