# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas_app', '0001_initial'),
        ('documentos_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HECHO_ECONO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor Comprobante')),
                ('descripcion', models.CharField(max_length=64, null=True, verbose_name='Descripción')),
                ('anulado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Anulado?')),
                ('protegido', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Protegido?')),
                ('fecha_prot', models.DateTimeField(auto_now=True, verbose_name='Fecha Protegido')),
                ('usuario', models.CharField(blank=True, max_length=16, null=True, verbose_name='Usuario')),
                ('canal', models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('CON', 'Consignación'), ('TRA', 'Transferencia'), ('GIR', 'Giro'), ('ATM', 'Red de Cajeros'), ('POS', 'Compras en Comercios'), ('IVR', 'Audio Respuesta'), ('WEB', 'Portal Transaccional'), ('MOV', 'Banca Móvil'), ('OFI', 'Oficina'), ('CNB', 'Corresponsales Bancarios'), ('RAL', 'Redes Aliadas'), ('N/A', 'No Aplica')], max_length=3, verbose_name='Canal')),
                ('cheque', models.CharField(max_length=16, null=True, verbose_name='Cheque')),
                ('beneficiario', models.CharField(max_length=12, null=True, verbose_name='Beneficiario')),
                ('id_ds', models.BigIntegerField(db_index=True, null=True, verbose_name='id_ds')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas_app.plan_ctas', verbose_name='Banco')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='localidades_app.localidades')),
                ('docto_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos_app.docto_conta', verbose_name='Documento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hecho_econo',
                'indexes': [models.Index(fields=['docto_conta', 'fecha'], name='hecho_econo_docto_c_2c1d27_idx')],
                'unique_together': {('docto_conta', 'numero')},
            },
        ),
    ]
