# Generated by Django 4.2.4 on 2024-06-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
        ('documentos_app', '0001_initial'),
        ('cuentas_app', '0001_initial'),
        ('hecho_economico_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho_econo',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas_app.plan_ctas', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='hecho_econo',
            name='beneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terceros_app.terceros', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='hecho_econo',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localidades_app.localidades', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='hecho_econo',
            name='valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Anulado?'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='canal',
            field=models.CharField(choices=[('ATM', 'Red de Cajeros'), ('POS', 'Compras en Comercios'), ('IVR', 'Audio Respuesta'), ('TRA', 'Transferencia'), ('CON', 'Consignación'), ('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('GIR', 'Giro'), ('WEB', 'Portal Transaccional'), ('MOV', 'Banca Móvil'), ('OFI', 'Oficina'), ('CNB', 'Corresponsales Bancarios'), ('RAL', 'Redes Aliadas')], max_length=3, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='docto_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos_app.docto_conta', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='protegido',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Protegido?'),
        ),
    ]
