# Generated by Django 4.2.4 on 2024-08-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hecho_economico_app', '0002_hecho_econo_banco_hecho_econo_beneficiario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hecho_econo',
            name='valor',
        ),
        migrations.AddField(
            model_name='hecho_econo',
            name='cheque',
            field=models.CharField(max_length=16, null=True, verbose_name='Cheque'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='beneficiario',
            field=models.CharField(max_length=12, null=True, verbose_name='Beneficiario'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='canal',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('CON', 'Consignación'), ('TRA', 'Transferencia'), ('GIR', 'Giro'), ('ATM', 'Red de Cajeros'), ('POS', 'Compras en Comercios'), ('IVR', 'Audio Respuesta'), ('WEB', 'Portal Transaccional'), ('MOV', 'Banca Móvil'), ('OFI', 'Oficina'), ('CNB', 'Corresponsales Bancarios'), ('RAL', 'Redes Aliadas')], max_length=3, verbose_name='Canal'),
        ),
    ]
