# Generated by Django 4.2.4 on 2024-10-24 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
        ('hecho_economico_app', '0003_remove_hecho_econo_valor_hecho_econo_cheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho_econo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas_app.plan_ctas', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localidades_app.localidades'),
        ),
    ]
