# Generated by Django 4.2.4 on 2024-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hecho_economico_app', '0004_hecho_econo_user_alter_hecho_econo_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho_econo',
            name='usuario',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Usuario'),
        ),
    ]
