# Generated by Django 4.2.4 on 2024-11-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hecho_economico_app', '0005_alter_hecho_econo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho_econo',
            name='valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Comprobante'),
        ),
    ]
