# Generated by Django 4.2.4 on 2024-12-24 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
        ('documentos_app', '0002_docto_conta_num_automatico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hecho_economico_app', '0006_hecho_econo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho_econo',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas_app.plan_ctas', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='localidades_app.localidades'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='docto_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos_app.docto_conta', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
