# Generated by Django 4.2.4 on 2025-03-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hecho_economico_app', '0007_alter_hecho_econo_banco_alter_hecho_econo_ciudad_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hecho_econo',
            index=models.Index(fields=['docto_conta', 'fecha'], name='hecho_econo_docto_c_2c1d27_idx'),
        ),
    ]
