# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMP_CON_CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_imp', models.CharField(max_length=2, null=True, verbose_name='Código')),
                ('cod_mod', models.CharField(max_length=1, null=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=40, null=True, verbose_name='Descripción')),
                ('kpte_cap', models.CharField(max_length=10, null=True, verbose_name='Cuenta Puente Capital')),
                ('kdet_gen_adi', models.CharField(max_length=10, null=True, verbose_name='Provisión General Adicional')),
                ('kdet_gen', models.CharField(max_length=10, null=True, verbose_name='Provisión General')),
                ('kdet_gen_gas', models.CharField(max_length=10, null=True, verbose_name='Cuenta Gasto Provisión')),
                ('kdet_gen_rec', models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Recuperada')),
                ('kdet_ind_gas', models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Individual Gasto')),
                ('kdet_ind_rec', models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Individual Recuperada')),
                ('kdpp_ic', models.CharField(max_length=10, null=True, verbose_name='Cuenta Descuento Pronto Pago IC')),
                ('kpte_ic', models.CharField(max_length=10, null=True, verbose_name='Cuenta Puente IC')),
                ('cta_val', models.CharField(max_length=10, null=True, verbose_name='Cuenta Valorización')),
                ('kcta_ingreso', models.CharField(max_length=10, null=True, verbose_name='Cuenta Ingresos')),
                ('kic_orden_i', models.CharField(max_length=10, null=True, verbose_name='Cuenta de Orden IC')),
                ('kic_cxp', models.CharField(max_length=10, null=True, verbose_name='Cuenta por Pagar')),
                ('kic_rec_int', models.CharField(max_length=10, null=True, verbose_name='Cuenta por Pagar')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'imp_con_cre',
                'unique_together': {('cliente', 'cod_imp')},
            },
        ),
        migrations.CreateModel(
            name='MODALIDADES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_mod', models.CharField(max_length=1, null=True, verbose_name='Código')),
                ('num_rango', models.IntegerField(blank=True, default=0, null=True, verbose_name='Num Rango')),
                ('cod_cta', models.CharField(max_length=10, null=True, verbose_name='Cuenta de Orden')),
                ('max_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Num Rango')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'modalidades',
                'unique_together': {('cliente', 'cod_mod', 'num_rango')},
            },
        ),
    ]
