# Generated by Django 4.2.4 on 2025-04-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0005_rename_fec_ulp_pag_xmov_cre_fec_ult_pag_and_more'),
        ('contabilizacion_capital_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MADALIDADES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_mod', models.CharField(max_length=1, null=True, verbose_name='Código')),
                ('num_rango', models.IntegerField(blank=True, default=0, null=True, verbose_name='Num Rango')),
                ('cod_cta', models.CharField(max_length=10, null=True, verbose_name='Cuenta de Orden')),
                ('max_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Num Rango')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'modalidades',
                'unique_together': {('cliente', 'cod_mod')},
            },
        ),
    ]
