# Generated by Django 4.2.4 on 2025-04-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilizacion_capital_creditos_app', '0002_madalidades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MADALIDADES',
        ),
    ]
