# Generated by Django 4.2.4 on 2025-04-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilizacion_capital_creditos_app', '0004_modalidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_con_cre',
            name='cod_mod',
            field=models.CharField(max_length=1, null=True, verbose_name='Código'),
        ),
    ]
