# Generated by Django 4.2.4 on 2025-04-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilizacion_capital_creditos_app', '0005_imp_con_cre_cod_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_con_cre',
            name='kic_cxp',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta por Pagar'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kic_rec_int',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta por Pagar'),
        ),
    ]
