"""
Django settings for justo_proy project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from decouple import config

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1fhj!^y9g(eer3$1oki$m#m*ob$g67*%1+y8o-ml^np59ocugo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECRET_KEY = config('SECRET_KEY')
# DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backup_app',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'activos_fijos_app',
    'auditoria_app',
    'ampliacion_cdat_app',
    'aportes_app',
    'asociados_app',
    'cambios_creditos_app',
    'categorias_creditos_app',
    'causacion_creditos_app',
    'cdat_app',
    # 'celery_app',
    'centrocostos_app',
    'cierre_mensual_app',
    'ciiu_app',
    'clientes_app',
    'conceptos_app',
    'contabilidad_app',
    'contabilizacion_capital_creditos_app',
    'contabilizacion_intereses_creditos_app',
    'contabilizacion_lineas_ahorros_app',
    'creditos_app',
    'ctas_ahorros_app',
    'cuentas_app',
    'cajeros_app',
    'destino_credito_app',
    'detalle_economico_app',
    'detalle_producto_app',
    'documentos_app',
    'estados_financieros_app',
    'hecho_economico_app',
    'historico_ctas_ahorros_app',
    'justo_app',
    'lineas_ahorro_app',
    'lineas_credito_app',
    'liquidacion_cdat_app',
    'localidades_app',
    'movimiento_caja_app',
    'oficinas_app',
    'originacion_app',
    'pagadores_app',
    'retefuente_ahorros_app',
    'tasas_lin_aho_app',
    'terceros_app',
    'usuarios_app',
    'recla_carte_app',
    'cxc_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'justo_proy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'justo_proy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
