# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion
import justo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TERCEROS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_doc', models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('T', 'Tarjeta de Identidad'), ('N', 'Nit'), ('R', 'Registro Civil'), ('E', 'Cédula de Extranjería'), ('P', 'Pasaporte'), ('O', 'Otros')], max_length=1, verbose_name='Tipo Documento')),
                ('doc_ide', models.CharField(max_length=12, verbose_name='Número Documento')),
                ('dig_ver', models.CharField(blank=True, max_length=1, verbose_name='DV')),
                ('nit_rap', models.CharField(blank=True, max_length=12, verbose_name='Nit Rápido')),
                ('regimen', models.CharField(choices=[('48', 'Responsable'), ('49', 'No Responsable'), ('Comun', 'Común')], max_length=12, verbose_name='Tipo Régimen')),
                ('fec_exp_ced', models.DateField(blank=True, null=True, verbose_name='Fecha Expedición Documento')),
                ('tip_ter', models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica'), ('O', 'Otro')], max_length=12, verbose_name='Tipo Tercero')),
                ('pri_ape', models.CharField(max_length=28, null=True, verbose_name='Primer Apellido')),
                ('seg_ape', models.CharField(blank=True, max_length=28, verbose_name='Segundo Apellido')),
                ('pri_nom', models.CharField(max_length=28, null=True, verbose_name='Primer Nombre')),
                ('seg_nom', models.CharField(blank=True, max_length=28, verbose_name='Segundo Nombre')),
                ('raz_soc', models.CharField(blank=True, max_length=120, verbose_name='Razón Social')),
                ('direccion', models.CharField(max_length=80, null=True, verbose_name='Dirección')),
                ('cod_pos', models.CharField(max_length=8, null=True, verbose_name='Código Postal')),
                ('tel_ofi', models.CharField(max_length=10, null=True, verbose_name='Teléfono Oficina')),
                ('tel_res', models.CharField(max_length=10, null=True, verbose_name='Teléfono Residencia')),
                ('id_ds', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('celular1', models.CharField(help_text='El número de celular debe contener exactamente 10 dígitos numéricos.', max_length=10, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Celular 1')),
                ('celular2', models.CharField(max_length=10, null=True, verbose_name='Celular 2')),
                ('fax', models.CharField(max_length=10, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('fec_act', models.DateField(blank=True, null=True, verbose_name='Fecha Actualización')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observación')),
                ('per_pub_exp', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Persona Expuesta PEP')),
                ('nit_interno', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Nit Interno')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
                ('cod_ciu_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_exp', to='localidades_app.localidades', verbose_name='Ciudad Expedición Documento')),
                ('cod_ciu_res', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_res', to='localidades_app.localidades', verbose_name='Ciudad Residencia')),
            ],
            options={
                'db_table': 'terceros',
                'unique_together': {('cliente', 'cla_doc', 'doc_ide')},
            },
        ),
    ]
