# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
import justo_app.funciones_principales
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TERCEROS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cla_doc', models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('T', 'Tarjeta de Identidad'), ('N', 'Nit'), ('R', 'Registro Civil'), ('E', 'Cédula de Extranjería'), ('P', 'Pasaporte'), ('O', 'Otros')], max_length=1, verbose_name='Tipo Documento')),
                ('nacionalidad', models.CharField(blank=True, choices=[('013', 'AFGANISTAN'), ('017', 'ALBANIA'), ('023', 'ALEMANIA'), ('026', 'ARMENIA'), ('027', 'ARUBA'), ('029', 'BOSNIA-HERZEGOVINA'), ('031', 'BURKINA FASSO'), ('037', 'ANDORRA'), ('040', 'ANGOLA'), ('041', 'ANGUILLA'), ('043', 'ANTIGUA Y BARBUDA'), ('047', 'ANTILLAS HOLANDESAS'), ('053', 'ARABIA SAUDITA'), ('059', 'ARGELIA'), ('063', 'ARGENTINA'), ('069', 'AUSTRALIA'), ('072', 'AUSTRIA'), ('074', 'AZERBAIJAN'), ('077', 'BAHAMAS'), ('080', 'BAHREIN'), ('081', 'BANGLADESH'), ('083', 'BARBADOS'), ('087', 'BELGICA'), ('088', 'BELICE'), ('090', 'BERMUDAS'), ('091', 'BELARUS'), ('093', 'BIRMANIA (MYANMAR)'), ('097', 'BOLIVIA'), ('101', 'BOTSWANA'), ('105', 'BRASIL'), ('108', 'BRUNEI DARUSSALAM'), ('111', 'BULGARIA'), ('115', 'BURUNDI'), ('119', 'EãTAN'), ('127', 'CABO VERDE'), ('137', 'CAIMAN, ISLAS'), ('141', 'CAMBOYA (KAMPUCHEA)'), ('145', 'CAMERUN, REPUBLICA UNIDA DEL'), ('149', 'CANADA'), ('159', 'SANTA SEDE'), ('165', 'COCOS (KEELING), ISLAS'), ('169', 'COLOMBIA'), ('173', 'COMORAS'), ('177', 'CONGO'), ('183', 'COOK, ISLAS'), ('187', 'COREA (NORTE), REPUBLICA POPULAR DEMOCRATICA DE'), ('190', 'COREA (SUR), REPUBLICA DE'), ('193', 'COSTA DE MARFIL'), ('196', 'COSTA RICA'), ('198', 'CROACIA'), ('199', 'CUBA'), ('203', 'CHAD'), ('211', 'CHILE'), ('215', 'CHINA'), ('218', 'TAIWAN (FORMOSA)'), ('221', 'CHIPRE'), ('229', 'BENIN'), ('232', 'DINAMARCA'), ('235', 'DOMINICA'), ('239', 'ECUADOR'), ('240', 'EGIPTO'), ('242', 'EL SALVADOR'), ('243', 'ERITREA'), ('244', 'EMIRATOS ARABES UNIDOS'), ('245', 'ESPAÑA'), ('246', 'ESLOVAQUIA'), ('247', 'ESLOVENIA'), ('249', 'ESTADOS UNIDOS'), ('251', 'ESTONIA'), ('253', 'ETIOPIA'), ('259', 'FEROE, ISLAS'), ('267', 'FILIPINAS'), ('271', 'FINLANDIA'), ('275', 'FRANCIA'), ('281', 'GABON'), ('285', 'GAMBIA'), ('287', 'GEORGIA'), ('289', 'GHANA'), ('293', 'GIBRALTAR'), ('297', 'GRANADA'), ('301', 'GRECIA'), ('305', 'GROENLANDIA'), ('309', 'GUADALUPE'), ('313', 'GUAM'), ('317', 'GUATEMALA'), ('325', 'GUAYANA FRANCESA'), ('329', 'GUINEA'), ('331', 'GUINEA ECUATORIAL'), ('334', 'GUINEA-BISSAU'), ('337', 'GUYANA'), ('341', 'HAITI'), ('345', 'HONDURAS'), ('351', 'HONG KONG'), ('355', 'HUNGRIA'), ('361', 'INDIA'), ('365', 'INDONESIA'), ('369', 'IRAK'), ('372', 'IRAN, REPUBLICA ISLAMICA DEL'), ('375', 'IRLANDA (EIRE)'), ('379', 'ISLANDIA'), ('383', 'ISRAEL'), ('386', 'ITALIA'), ('391', 'JAMAICA'), ('399', 'JAPON'), ('403', 'JORDANIA'), ('406', 'KAZAJSTAN'), ('410', 'KENIA'), ('411', 'KIRIBATI'), ('412', 'KIRGUIZISTAN'), ('413', 'KUWAIT'), ('420', 'LAOS, REPUBLICA POPULAR DEMOCRATICA DE'), ('426', 'LESOTHO'), ('429', 'LETONIA'), ('431', 'LIBANO'), ('434', 'LIBERIA'), ('438', 'LIBIA (INCLUYE FEZZAN)'), ('440', 'LIECHTENSTEIN'), ('443', 'LITUANIA'), ('445', 'LUXEMBURGO'), ('447', 'MACAO'), ('448', 'MACEDONIA'), ('450', 'MADAGASCAR'), ('455', 'MALAYSIA'), ('458', 'MALAWI'), ('461', 'MALDIVAS'), ('464', 'MALI'), ('467', 'MALTA'), ('469', 'MARIANAS DEL NORTE, ISLAS'), ('472', 'MARSHALL, ISLAS'), ('474', 'MARRUECOS'), ('477', 'MARTINICA'), ('485', 'MAURICIO'), ('488', 'MAURITANIA'), ('493', 'MEXICO'), ('494', 'MICRONESIA, ESTADOS FEDERADOS DE'), ('496', 'MOLDAVIA'), ('497', 'MONGOLIA'), ('498', 'MONACO'), ('501', 'MONSERRAT, ISLA'), ('505', 'MOZAMBIQUE'), ('507', 'NAMIBIA'), ('508', 'NAURU'), ('511', 'NAVIDAD (CHRISTMAS), ISLAS'), ('517', 'NEPAL'), ('521', 'NICARAGUA'), ('525', 'NIGER'), ('528', 'NIGERIA'), ('531', 'NIUE, ISLA'), ('535', 'NORFOLK, ISLA'), ('538', 'NORUEGA'), ('542', 'NUEVA CALEDONIA'), ('545', 'PAPUASIA NUEVA GUINEA'), ('548', 'NUEVA ZELANDIA'), ('551', 'VANUATU'), ('556', 'OMAN'), ('566', 'PACIFICO, ISLAS (USA)'), ('573', 'PAISES BAJOS (HOLANDA)'), ('576', 'PAKISTAN'), ('578', 'PALAU, ISLAS'), ('580', 'PANAMA'), ('586', 'PARAGUAY'), ('589', 'PERU'), ('593', 'PITCAIRN, ISLA'), ('599', 'POLINESIA FRANCESA'), ('603', 'POLONIA'), ('607', 'PORTUGAL'), ('611', 'PUERTO RICO'), ('618', 'QATAR'), ('628', 'REINO UNIDO'), ('640', 'REPUBLICA CENTROAFRICANA'), ('644', 'REPUBLICA CHECA'), ('647', 'REPUBLICA DOMINICANA'), ('660', 'REUNION'), ('665', 'ZIMBABWE'), ('670', 'RUMANIA'), ('675', 'RUANDA'), ('676', 'RUSIA'), ('677', 'SALOMON, ISLAS'), ('685', 'SAHARA OCCIDENTAL'), ('687', 'SAMOA'), ('690', 'SAMOA NORTEAMERICANA'), ('695', 'SAN CRISTOBAL Y NIEVES'), ('697', 'SAN MARINO'), ('700', 'SAN PEDRO Y MIGUELON'), ('705', 'SAN VICENTE Y LAS GRANADINAS'), ('710', 'SANTA ELENA'), ('715', 'SANTA LUCIA'), ('720', 'SANTO TOME Y PRINCIPE'), ('728', 'SENEGAL'), ('731', 'SEYCHELLES'), ('735', 'SIERRA LEONA'), ('741', 'SINGAPUR'), ('744', 'SIRIA, REPUBLICA ARABE DE'), ('748', 'SOMALIA'), ('750', 'SRI LANKA'), ('756', 'SUDAFRICA, REPUBLICA DE'), ('759', 'SUDAN'), ('764', 'SUECIA'), ('767', 'SUIZA'), ('770', 'SURINAM'), ('773', 'SWAZILANDIA'), ('774', 'TADJIKISTAN'), ('776', 'TAILANDIA'), ('780', 'TANZANIA, REPUBLICA UNIDA DE'), ('783', 'DJIBOUTI'), ('787', 'TERRITORIO BRITANICO DEL OCEANO INDICO'), ('788', 'TIMOR DEL ESTE'), ('800', 'TOGO'), ('805', 'TOKELAU'), ('810', 'TONGA'), ('815', 'TRINIDAD Y TOBAGO'), ('820', 'TUNICIA'), ('823', 'TURCAS Y CAICOS, ISLAS'), ('825', 'TURKMENISTAN'), ('827', 'TURQUIA'), ('828', 'TUVALU'), ('830', 'UCRANIA'), ('833', 'UGANDA'), ('845', 'URUGUAY'), ('847', 'UZBEKISTAN'), ('850', 'VENEZUELA'), ('855', 'VIET NAM'), ('863', 'VIRGENES, ISLAS (BRITANICAS)'), ('866', 'VIRGENES, ISLAS (NORTEAMERICANAS)'), ('870', 'FIJI'), ('875', 'WALLIS Y FORTUNA, ISLAS'), ('880', 'YEMEN'), ('885', 'YUGOSLAVIA'), ('888', 'ZAIRE'), ('890', 'ZAMBIA'), ('897', 'ZONA NEUTRAL PALESTINA')], default='169', max_length=3, null=True, verbose_name='Nacionalidad')),
                ('doc_ide', models.CharField(max_length=12, verbose_name='Número Documento')),
                ('dig_ver', models.CharField(blank=True, max_length=1, verbose_name='DV')),
                ('fec_exp_ced', models.DateField(blank=True, null=True, verbose_name='Fecha Expedición Documento')),
                ('tip_ter', models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica'), ('O', 'Otro')], max_length=1, verbose_name='Tipo Tercero')),
                ('tip_vinculo', models.CharField(choices=[('0', 'No Aplica'), ('1', 'Proveedor'), ('2', 'Empleado'), ('3', 'Asociado')], default='0', max_length=1, verbose_name='Vínculo')),
                ('pri_ape', models.CharField(max_length=28, null=True, verbose_name='Primer Apellido')),
                ('seg_ape', models.CharField(blank=True, max_length=28, verbose_name='Segundo Apellido')),
                ('pri_nom', models.CharField(max_length=28, null=True, verbose_name='Primer Nombre')),
                ('seg_nom', models.CharField(blank=True, max_length=28, verbose_name='Segundo Nombre')),
                ('regimen', models.CharField(choices=[('48', 'Responsable'), ('49', 'No Responsable'), ('Comun', 'Común')], default='49', max_length=12, verbose_name='Tipo Régimen')),
                ('raz_soc', models.CharField(blank=True, max_length=120, verbose_name='Razón Social')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('celular1', models.CharField(help_text='El número de celular debe contener exactamente 10 dígitos numéricos.', max_length=10, null=True, validators=[justo_app.funciones_principales.validate_numeric], verbose_name='Celular Principal')),
                ('celular2', models.CharField(blank=True, max_length=10, verbose_name='Celular Secundario')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('tel_ofi', models.CharField(blank=True, max_length=10, verbose_name='Teléfono Oficina')),
                ('tel_res', models.CharField(blank=True, max_length=10, verbose_name='Teléfono Residencia')),
                ('cod_pos', models.CharField(blank=True, max_length=8, verbose_name='Código Postal')),
                ('per_pub_exp', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Persona Expuesta PEP')),
                ('fec_pep', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio PEP')),
                ('cargo_pep', models.CharField(blank=True, max_length=60, null=True, verbose_name='Cargo')),
                ('fec_fin_pep', models.DateField(blank=True, null=True, verbose_name='Fecha Fin PEP')),
                ('grupo_especial', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Pertenece a algún grupo de protección especial constitucional?')),
                ('grupos_especiales', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'No Aplica'), ('1', 'Niños, niñas y adolescentes'), ('2', 'Mayores de 60 años'), ('3', 'Persona con discapacidad física, mental o sensorial'), ('4', 'Mujer cabeza de familia'), ('5', 'Víctima del conflicto armado'), ('6', 'Persona en condición de pobreza extrema'), ('7', 'Pueblos indígenas'), ('8', 'Población diversa / LGBTIQ+'), ('9', 'Población Afrocolombiana')], max_length=60, null=True, verbose_name='Cuáles ?')),
                ('proceso_judicial', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='Está vinculado a un proceso judicial penal Ley 1908 2018?')),
                ('fec_act', models.DateField(blank=True, null=True, verbose_name='Fecha Actualización')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observación')),
                ('tipo_asesoria', models.CharField(blank=True, choices=[('1', 'Oficina'), ('2', 'Externa'), ('3', 'Telefónica'), ('4', 'Virtual')], default='1', max_length=1, null=True, verbose_name='Tipo Asesoría')),
                ('nit_rap', models.CharField(blank=True, max_length=12, verbose_name='Nit Rápido')),
                ('id_ds', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=10, verbose_name='Fax')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre')),
                ('nit_interno', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Nit Interno')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
                ('cod_ciu_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_exp', to='localidades_app.localidades', verbose_name='Ciudad Expedición Documento')),
                ('cod_ciu_res', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_res', to='localidades_app.localidades', verbose_name='Ciudad Residencia')),
                ('usuario_asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usaurio_asesor', to=settings.AUTH_USER_MODEL, verbose_name='Asesor')),
            ],
            options={
                'db_table': 'terceros',
                'indexes': [models.Index(fields=['cliente'], name='terceros_cliente_eed075_idx'), models.Index(fields=['nombre'], name='terceros_nombre_d2429c_idx')],
                'unique_together': {('cliente', 'doc_ide')},
            },
        ),
    ]
