# Generated by Django 4.2.4 on 2024-10-24 10:26

from django.db import migrations, models
import justo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='celular1',
            field=models.CharField(help_text='El número de celular debe contener exactamente 10 dígitos numéricos.', max_length=10, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Celular Principal'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='celular2',
            field=models.CharField(max_length=10, null=True, verbose_name='Celular Secundario'),
        ),
    ]
