# Generated by Django 4.2.4 on 2024-11-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0002_alter_terceros_celular1_alter_terceros_celular2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tip_ter',
            field=models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica'), ('O', 'Otro')], max_length=1, verbose_name='Tipo Tercero'),
        ),
    ]
