# Generated by Django 4.2.4 on 2024-12-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0003_alter_terceros_tip_ter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tip_ter',
            field=models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica'), ('O', 'Otro')], max_length=12, verbose_name='Tipo Tercero'),
        ),
    ]
