# Generated by Django 4.2.4 on 2025-01-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0004_alter_terceros_tip_ter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terceros',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
