# Generated by Django 4.2.4 on 2025-03-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0005_alter_terceros_unique_together_alter_terceros_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='tip_ter',
            field=models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica'), ('O', 'Otro')], max_length=1, verbose_name='Tipo Tercero'),
        ),
    ]
