# Generated by Django 5.2 on 2025-05-20 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0005_rename_fec_ulp_pag_xmov_cre_fec_ult_pag_and_more'),
        ('terceros_app', '0006_alter_terceros_tip_ter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terceros',
            unique_together={('cliente', 'doc_ide')},
        ),
    ]
