# Generated by Django 5.2 on 2025-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0005_rename_fec_ulp_pag_xmov_cre_fec_ult_pag_and_more'),
        ('localidades_app', '0001_initial'),
        ('terceros_app', '0007_alter_terceros_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='terceros',
            index=models.Index(fields=['cliente'], name='terceros_cliente_eed075_idx'),
        ),
        migrations.AddIndex(
            model_name='terceros',
            index=models.Index(fields=['nombre'], name='terceros_nombre_d2429c_idx'),
        ),
    ]
