# Generated by Django 5.2 on 2025-06-10 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0008_terceros_terceros_cliente_eed075_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='celular2',
            field=models.CharField(max_length=10, verbose_name='Celular Secundario'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_pos',
            field=models.CharField(max_length=8, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fax',
            field=models.CharField(max_length=10, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fec_act',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nit_interno',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Nit Interno'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='per_pub_exp',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Persona Expuesta PEP'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='regimen',
            field=models.CharField(choices=[('48', 'Responsable'), ('49', 'No Responsable'), ('Comun', 'Común')], default='49', max_length=12, verbose_name='Tipo Régimen'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_ofi',
            field=models.CharField(max_length=10, verbose_name='Teléfono Oficina'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_res',
            field=models.CharField(max_length=10, verbose_name='Teléfono Residencia'),
        ),
    ]
