# Generated by Django 5.2 on 2025-06-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0009_alter_terceros_celular2_alter_terceros_cod_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='celular2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Secundario'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_pos',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='direccion',
            field=models.CharField(max_length=80, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fec_act',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_ofi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Oficina'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_res',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Residencia'),
        ),
    ]
