# Generated by Django 5.2 on 2025-06-10 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades_app', '0001_initial'),
        ('terceros_app', '0010_alter_terceros_celular2_alter_terceros_cod_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='celular2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Celular Secundario'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_exp',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_exp', to='localidades_app.localidades', verbose_name='Ciudad Expedición Documento'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_res',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_res', to='localidades_app.localidades', verbose_name='Ciudad Residencia'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_pos',
            field=models.CharField(blank=True, max_length=8, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fax',
            field=models.CharField(blank=True, max_length=10, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fec_act',
            field=models.DateField(blank=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_ofi',
            field=models.CharField(blank=True, max_length=10, verbose_name='Teléfono Oficina'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='tel_res',
            field=models.CharField(blank=True, max_length=10, verbose_name='Teléfono Residencia'),
        ),
    ]
