# Generated by Django 5.2 on 2025-06-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0011_alter_terceros_celular2_alter_terceros_cod_ciu_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
    ]
