# Generated by Django 5.2 on 2025-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0012_alter_terceros_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
    ]
