# Generated by Django 5.2 on 2025-06-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0013_alter_terceros_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='fec_exp_ced',
            field=models.DateField(blank=True, verbose_name='Fecha Expedición Documento'),
        ),
    ]
