# Generated by Django 5.2 on 2025-06-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades_app', '0001_initial'),
        ('terceros_app', '0014_alter_terceros_fec_exp_ced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_exp', to='localidades_app.localidades', verbose_name='Ciudad Expedición Documento'),
        ),
    ]
