# Generated by Django 5.2 on 2025-06-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0015_alter_terceros_cod_ciu_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='fec_act',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Actualización'),
        ),
    ]
