# Generated by Django 5.2 on 2025-06-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0016_alter_terceros_fec_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='fec_exp_ced',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Expedición Documento'),
        ),
    ]
