# Generated by Django 5.2 on 2025-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0017_alter_terceros_fec_exp_ced'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceros',
            name='cargo_pep',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='fec_pep',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio PEP'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='tip_vinculo',
            field=models.CharField(choices=[('0', 'No Aplica'), ('1', 'Proveedor'), ('2', 'Empleado'), ('3', 'Asociado')], default='0', max_length=1, verbose_name='Vínculo'),
        ),
    ]
