# Generated by Django 5.2 on 2025-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0018_terceros_cargo_pep_terceros_fec_pep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceros',
            name='fec_fin_pep',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin PEP'),
        ),
    ]
