# Generated by Django 5.2 on 2025-07-16 20:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0020_terceros_grupo_especial_terceros_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceros',
            name='grupos_especiales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'No Aplica'), ('1', 'Niños, niñas y adolescentes'), ('2', 'Mayores de 60 años'), ('3', 'Persona con discapacidad física, mental o sensorial'), ('4', 'Mujer cabeza de familia'), ('5', 'Víctima del conflicto armado'), ('6', 'Persona en condición de pobreza extrema'), ('7', 'Pueblos indígenas'), ('8', 'Población diversa / LGBTIQ+'), ('9', 'Población Afrocolombiana')], default='0', max_length=60, null=True, verbose_name='Cuáles ?'),
        ),
    ]
