# Generated by Django 5.2 on 2025-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0021_terceros_grupos_especiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceros',
            name='proceso_judicial',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='Está vinculado a un proceso judicial penal Ley 1908 2018?'),
        ),
    ]
