# Generated by Django 5.2 on 2025-07-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0022_terceros_proceso_judicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='celular2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular Secundario'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='dig_ver',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nit_rap',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nit Rápido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='raz_soc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_ape',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_nom',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
