# Generated by Django 5.2 on 2025-07-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0023_alter_terceros_celular2_alter_terceros_dig_ver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='celular2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Celular Secundario'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='dig_ver',
            field=models.CharField(blank=True, max_length=1, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='fax',
            field=models.CharField(blank=True, max_length=10, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='raz_soc',
            field=models.CharField(blank=True, max_length=120, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_ape',
            field=models.CharField(blank=True, max_length=28, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_nom',
            field=models.CharField(blank=True, max_length=28, verbose_name='Segundo Nombre'),
        ),
    ]
