# Generated by Django 5.2 on 2025-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0024_alter_terceros_celular2_alter_terceros_dig_ver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='nit_rap',
            field=models.CharField(blank=True, max_length=12, verbose_name='Nit Rápido'),
        ),
    ]
