# Generated by Django 5.2 on 2025-07-25 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0025_alter_terceros_nit_rap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terceros',
            name='tipo_asesoria',
            field=models.CharField(blank=True, choices=[('1', 'Oficina'), ('2', 'Externa'), ('3', 'Telefónica'), ('4', 'Virtual')], default='1', max_length=1, null=True, verbose_name='Tipo Asesoría'),
        ),
        migrations.AddField(
            model_name='terceros',
            name='usuario_asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usaurio_asesor', to=settings.AUTH_USER_MODEL, verbose_name='Asesor'),
        ),
    ]
