# Generated by Django 5.2 on 2025-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0026_terceros_tipo_asesoria_terceros_usuario_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='grupo_especial',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Pertenece a algún grupo de protección especial constitucional?'),
        ),
    ]
