# Generated by Django 5.2 on 2025-07-25 20:05

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0027_alter_terceros_grupo_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='grupo_especial',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Pertenece a algún grupo de protección especial constitucional?'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='grupos_especiales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'No Aplica'), ('1', 'Niños, niñas y adolescentes'), ('2', 'Mayores de 60 años'), ('3', 'Persona con discapacidad física, mental o sensorial'), ('4', 'Mujer cabeza de familia'), ('5', 'Víctima del conflicto armado'), ('6', 'Persona en condición de pobreza extrema'), ('7', 'Pueblos indígenas'), ('8', 'Población diversa / LGBTIQ+'), ('9', 'Población Afrocolombiana')], max_length=60, null=True, verbose_name='Cuáles ?'),
        ),
    ]
