# Generated by Django 5.2 on 2025-07-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0028_alter_terceros_grupo_especial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='nit_interno',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Nit Interno'),
        ),
    ]
