# Generated by Django 5.2.13 on 2026-06-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOCALIDADES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, verbose_name='Código')),
                ('nombre', models.CharField(max_length=36, verbose_name='Ciudad')),
                ('cod_pos', models.CharField(max_length=12, null=True, verbose_name='Código Postal')),
                ('departamento', models.CharField(max_length=36, null=True, verbose_name='Departamento')),
            ],
            options={
                'db_table': 'localidades',
                'unique_together': {('codigo',)},
            },
        ),
    ]
