# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONCEPTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_con', models.CharField(max_length=8, verbose_name='Código Concepto')),
                ('con_justo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Concepto Justo')),
                ('descripcion', models.CharField(max_length=44, verbose_name='Descripción')),
                ('tip_dev_ap', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tipo Devolución Aportes')),
                ('tip_con', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tipo Concepto')),
                ('tip_sis', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tipo Sistema')),
                ('cta_con', models.CharField(blank=True, max_length=10, verbose_name='Cuenta Contable')),
                ('cta_con_pas', models.CharField(blank=True, max_length=10, verbose_name='Cuenta Contable Pasivo')),
                ('debito', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Concepto Débito?')),
                ('credito', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Concepto Crédito?')),
                ('por_tercero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Usa Tercero?')),
                ('por_ret_fue', models.FloatField(blank=True, null=True, verbose_name='% Retefuente?')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'conceptos',
                'unique_together': {('cliente', 'cod_con')},
            },
        ),
    ]
