# Generated by Django 4.2.4 on 2024-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docto_conta',
            name='num_automatico',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Numeracion Autoatica?'),
        ),
    ]
