# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociados_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORIGINACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lin_cre', models.CharField(max_length=80, verbose_name='Línea de Crédito')),
                ('monto', models.FloatField(blank=True, null=True, verbose_name='Monto')),
                ('plazo', models.IntegerField(blank=True, null=True, verbose_name='Plazo')),
                ('gar_cre_sol', models.CharField(max_length=1, verbose_name='Garantía Crédito Solidario?')),
                ('lin_cre_sol', models.CharField(max_length=1, verbose_name='Línea Crédito Solidario')),
                ('mod_cre_sol', models.CharField(max_length=1, verbose_name='Modalidad Crédito Solidario')),
                ('sol_cre_edu', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Solicitud de credito')),
                ('for_pag', models.CharField(choices=[('P', 'Personal'), ('L', 'Libranza'), ('T', 'Transferencia')], default='P', max_length=1, verbose_name='Forma de pago')),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado')),
            ],
            options={
                'db_table': 'originacion',
                'unique_together': {('asociado',)},
            },
        ),
    ]
