# Generated by Django 4.2.4 on 2024-09-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originacion',
            name='for_pag',
            field=models.CharField(choices=[('P', 'Personal'), ('L', 'Libranza'), ('T', 'Transferencia')], default='P', max_length=1, verbose_name='Modalidad Crédito Solidario'),
        ),
        migrations.AddField(
            model_name='originacion',
            name='sol_cre_edu',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Modalidad Crédito Solidario'),
        ),
    ]
