# Generated by Django 4.2.4 on 2024-12-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originacion_app', '0002_originacion_for_pag_originacion_sol_cre_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originacion',
            name='for_pag',
            field=models.CharField(choices=[('P', 'Personal'), ('L', 'Libranza'), ('T', 'Transferencia')], default='P', max_length=1, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='originacion',
            name='sol_cre_edu',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Solicitud de credito'),
        ),
    ]
