# Generated by Django 5.2.13 on 2026-05-27 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'backup',
                'unique_together': {('timestamp',)},
            },
        ),
    ]
