# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16, verbose_name='Nombre Usuario')),
                ('nit', models.CharField(max_length=12, null=True, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=44, null=True, verbose_name='Nombre Completo')),
                ('fec_ing', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('es_cajero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Es Cajero?')),
                ('cod_caj', models.CharField(max_length=2, null=True, verbose_name='Código Cajero')),
                ('fec_sal', models.DateField(blank=True, null=True, verbose_name='Fecha Saldo')),
                ('cta_con_acr', models.CharField(max_length=10, null=True, verbose_name='Cuenta Contable')),
                ('activo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Está Activo?')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'usuarios',
                'unique_together': {('oficina', 'login')},
            },
        ),
    ]
