# Generated by Django 4.2.4 on 2024-07-06 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERFIL_USUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'unique_together': {('usuario',)},
            },
        ),
    ]
