# Generated by Django 4.2.4 on 2024-10-24 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0002_alter_terceros_celular1_alter_terceros_celular2'),
        ('oficinas_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios_app', '0002_perfil_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('es_cajero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Es Cajero?')),
                ('fec_ing', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso Cajero')),
                ('fec_ret', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro Cajero')),
                ('activo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Está Activo?')),
                ('cta_con_caj', models.CharField(max_length=10, null=True, verbose_name='Cuenta Contable')),
                ('cta_con_acr', models.CharField(max_length=10, null=True, verbose_name='Cuenta Contable')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
                ('terecero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Oficina')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='USUARIOS',
        ),
    ]
