# Generated by Django 4.2.4 on 2024-10-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0003_userprofile_delete_usuarios'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
