# Generated by Django 4.2.4 on 2024-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cta_con_acr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cta_con_caj',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='es_cajero',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fec_ing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fec_ret',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='terecero',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PERFIL_USUARIO',
        ),
    ]
