# Generated by Django 4.2.4 on 2024-09-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0003_alter_clientes_clase_coop'),
        ('localidades_app', '0001_initial'),
        ('terceros_app', '0001_initial'),
        ('estados_financieros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados_fin',
            name='act_vivienda',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True, verbose_name='Tiene Activos de Vivienda?'),
        ),
        migrations.AddField(
            model_name='estados_fin',
            name='otros_pasivos',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True, verbose_name='Tiene otros pasivos?'),
        ),
        migrations.AddField(
            model_name='estados_fin',
            name='tiene_inversiones',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True, verbose_name='Tiene Inversiones?'),
        ),
        migrations.AlterField(
            model_name='estados_fin',
            name='ing_ext',
            field=models.FloatField(blank=True, null=True, verbose_name='Otros Ingresos'),
        ),
        migrations.CreateModel(
            name='ACTIVOS_TER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_bien', models.CharField(blank=True, max_length=20, verbose_name='Tipo de Inmueble')),
                ('val_comercial', models.FloatField(null=True, verbose_name='Valor Comercial')),
                ('hipotecado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Hipotecado o Picnorado')),
                ('hipotecado_a', models.CharField(max_length=50, verbose_name='Hipotecado a ')),
                ('val_hipoteca', models.FloatField(null=True, verbose_name='Valor Comercial')),
                ('direccion', models.CharField(blank=True, max_length=60, verbose_name='Tipo de Inmueble')),
                ('matricula', models.CharField(max_length=20, verbose_name='matricula inmoviliaria ')),
                ('ident_activo', models.CharField(max_length=30, verbose_name='Matricula/Placa')),
                ('otros_ident', models.CharField(max_length=30, verbose_name='Modelo u otros')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='localidades_app.localidades', verbose_name='Tercero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
                ('tercero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Tercero')),
            ],
            options={
                'db_table': 'activos_ter',
                'unique_together': {('cliente', 'tercero', 'tip_bien')},
            },
        ),
    ]
