# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centrocostos_app', '0001_initial'),
        ('hecho_economico_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLE_PROD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('AP', 'Aportes'), ('AH', 'Ahorros'), ('CR', 'Créditos'), ('CC', 'Cuenta por Cobrar'), ('CP', 'Cuenta por Pagar'), ('CO', 'Contable'), ('BA', 'Bancos')], max_length=2, verbose_name='Producto')),
                ('subcuenta', models.CharField(max_length=12, null=True, verbose_name='Subcuenta')),
                ('concepto', models.CharField(max_length=8, null=True, verbose_name='Concepto')),
                ('valor', models.FloatField(null=True, verbose_name='Valor')),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='centrocostos_app.centrocostos', verbose_name='Centro de Costo')),
                ('hecho_econo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='hecho_economico_app.hecho_econo', verbose_name='Documento')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'detalle_prod',
                'indexes': [models.Index(fields=['oficina', 'producto', 'subcuenta'], name='detalle_pro_oficina_9a63d9_idx'), models.Index(fields=['producto', 'subcuenta', 'hecho_econo'], name='detalle_pro_product_6f75a1_idx')],
                'unique_together': {('hecho_econo', 'producto', 'subcuenta', 'concepto')},
            },
        ),
    ]
