# Generated by Django 4.2.4 on 2024-10-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_producto_app', '0002_alter_detalle_prod_hecho_econo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_prod',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='detalle_prod',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='detalle_prod',
            name='usuario',
        ),
    ]
