# Generated by Django 4.2.4 on 2025-03-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_producto_app', '0003_remove_detalle_prod_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detalle_prod',
            index=models.Index(fields=['producto', 'subcuenta', 'hecho_econo'], name='detalle_pro_product_6f75a1_idx'),
        ),
    ]
