# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociados_app', '0001_initial'),
        ('hecho_economico_app', '0001_initial'),
        ('lineas_ahorro_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAS_AHORRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True, verbose_name='Número Cuenta')),
                ('est_cta', models.CharField(choices=[('P', 'Por Aplicar'), ('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1, verbose_name='Estado Cuenta')),
                ('fec_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha Apertura')),
                ('fec_cancela', models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación')),
                ('exc_tas_mil', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Exenta 4x1000')),
                ('fec_ini_exc', models.DateField(blank=True, null=True, verbose_name='Fecha Exención')),
                ('cod_imp', models.CharField(blank=True, max_length=2, verbose_name='cod_imp')),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Nombre Asociado')),
                ('lin_aho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineas_ahorro_app.lineas_ahorro', verbose_name='Línea de Ahorro')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'ctas_ahorro',
                'unique_together': {('oficina', 'num_cta')},
            },
        ),
        migrations.CreateModel(
            name='TEMPO_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True)),
                ('agno', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tempo_aho',
                'unique_together': {('num_cta', 'agno', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='XAJU_SAL_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agno', models.IntegerField()),
                ('num_cta', models.CharField(max_length=10, null=True)),
                ('est_cta', models.CharField(choices=[('P', 'Por Aplicar'), ('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1, verbose_name='Estado Cuenta')),
                ('valor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'xaju_sal_aho',
                'unique_together': {('agno', 'num_cta')},
            },
        ),
        migrations.CreateModel(
            name='xTempo02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ide', models.CharField(max_length=12, null=True)),
                ('num_cta', models.CharField(max_length=10, null=True)),
                ('agno', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.FloatField()),
                ('valor_apl', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'xTempo02',
                'unique_together': {('agno', 'mes', 'doc_ide', 'num_cta')},
            },
        ),
        migrations.CreateModel(
            name='CANJE_AHORROS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True, verbose_name='Número Cuenta')),
                ('fecha_1', models.DateField(blank=True, null=True)),
                ('valor_1', models.BigIntegerField(null=True)),
                ('estado', models.CharField(choices=[('', '---------'), ('P', 'Pendiente'), ('C', 'Confirmado'), ('D', 'Devuelto')], max_length=1, null=True, verbose_name='Estado')),
                ('fecha_2', models.DateField(blank=True, null=True, verbose_name='Fecha Canje2')),
                ('valor_2', models.BigIntegerField(null=True)),
                ('aplicado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Aplicado')),
                ('hec_eco_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes_ahorros_comprob1', to='hecho_economico_app.hecho_econo', verbose_name='comprob1')),
                ('hec_eco_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canjes_ahorros_comprob2', to='hecho_economico_app.hecho_econo', verbose_name='comprob2')),
                ('oficina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro')),
            ],
            options={
                'db_table': 'canje_ahorros',
                'unique_together': {('oficina', 'cta_aho', 'hec_eco_1')},
            },
        ),
        migrations.CreateModel(
            name='INT_DIA_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True, verbose_name='Número Cuenta')),
                ('dia_mes', models.IntegerField(verbose_name='Día del Mes')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('int_dia', models.BigIntegerField(null=True, verbose_name='Interes Diario')),
                ('ret_fue', models.BigIntegerField(null=True, verbose_name='Retefuente')),
                ('aplicado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Aplicado')),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro')),
                ('oficina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'int_dia_aho',
                'unique_together': {('oficina', 'cta_aho', 'dia_mes')},
            },
        ),
    ]
