# Generated by Django 4.2.4 on 2024-06-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctas_ahorro',
            name='cod_imp',
            field=models.CharField(blank=True, max_length=2, verbose_name='cod_imp'),
        ),
    ]
