# Generated by Django 4.2.4 on 2024-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0002_ctas_ahorro_cod_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctas_ahorro',
            name='est_cta',
            field=models.CharField(choices=[('P', 'Por Aplicar'), ('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1, verbose_name='Estado Cuenta'),
        ),
    ]
