# Generated by Django 4.2.4 on 2024-12-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas_app', '0001_initial'),
        ('ctas_ahorros_app', '0003_alter_ctas_ahorro_est_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='INT_DIA_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True, verbose_name='Número Cuenta')),
                ('dia_mes', models.IntegerField(verbose_name='Día del Mes')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('int_dia', models.BigIntegerField(null=True, verbose_name='Interes Diario')),
                ('ret_fue', models.BigIntegerField(null=True, verbose_name='Retefuente')),
                ('aplicado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Aplicado')),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro')),
                ('oficina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'int_dia_aho',
                'unique_together': {('oficina', 'cta_aho', 'dia_mes')},
            },
        ),
    ]
