# Generated by Django 4.2.4 on 2025-02-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0004_int_dia_aho'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEMPO_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True)),
                ('agno', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tempo_aho',
                'unique_together': {('num_cta', 'agno', 'mes')},
            },
        ),
    ]
