# Generated by Django 4.2.4 on 2025-02-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0005_tempo_aho'),
    ]

    operations = [
        migrations.CreateModel(
            name='XAJU_SAL_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agno', models.IntegerField()),
                ('num_cta', models.CharField(max_length=10, null=True)),
                ('est_cta', models.CharField(choices=[('P', 'Por Aplicar'), ('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1, verbose_name='Estado Cuenta')),
                ('valor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'xjau_sal_aho',
                'unique_together': {('agno', 'num_cta')},
            },
        ),
    ]
