# Generated by Django 4.2.4 on 2025-03-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0006_xaju_sal_aho'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xaju_sal_aho',
            table='xaju_sal_aho',
        ),
    ]
