# Generated by Django 4.2.4 on 2025-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0007_alter_xaju_sal_aho_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='xTempo02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ide', models.CharField(max_length=12, null=True)),
                ('num_cta', models.CharField(max_length=10, null=True)),
                ('agno', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.BigIntegerField()),
                ('valor_apl', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'xTempo02',
                'unique_together': {('agno', 'mes', 'doc_ide')},
            },
        ),
    ]
