# Generated by Django 4.2.4 on 2025-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0008_xtempo02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xtempo02',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='xtempo02',
            name='valor_apl',
            field=models.FloatField(default=0),
        ),
    ]
