# Generated by Django 4.2.4 on 2025-03-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0009_alter_xtempo02_valor_alter_xtempo02_valor_apl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='xtempo02',
            unique_together={('agno', 'mes', 'doc_ide', 'num_cta')},
        ),
    ]
