# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
import justo_app.funciones_principales
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OFICINAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código Oficina')),
                ('contabiliza', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Contabiliza')),
                ('nombre_oficina', models.TextField(verbose_name='Nombre Oficina')),
                ('responsable', models.TextField(verbose_name='Responsable Oficina')),
                ('celular', models.CharField(help_text='El número de celular debe contener exactamente 10 dígitos numéricos.', max_length=10, null=True, validators=[justo_app.funciones_principales.validate_numeric], verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(max_length=80, null=True, verbose_name='Dirección')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidades_app.localidades', verbose_name='Ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'oficinas',
                'unique_together': {('cliente', 'codigo')},
            },
        ),
    ]
