# Generated by Django 4.2.4 on 2025-03-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conceptos_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
        ('terceros_app', '0005_alter_terceros_unique_together_alter_terceros_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAS_X_COBRAR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_cxc', models.CharField(max_length=10)),
                ('valor', models.FloatField(null=True)),
                ('fecha_des', models.DateField(blank=True, null=True)),
                ('fecha_exi', models.DateField(blank=True, null=True)),
                ('aplicado', models.CharField(choices=[('X', 'Por Causar'), ('A', 'Activo'), ('C', 'Cancelado'), ('T', 'Terminado Cupo')], max_length=1)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptos_app.conceptos')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros_app.terceros')),
            ],
            options={
                'db_table': 'ctas_x_cobrar',
                'unique_together': {('oficina', 'cod_cxc', 'concepto', 'tercero')},
            },
        ),
        migrations.CreateModel(
            name='CXC_DET',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tip_mov', models.CharField(max_length=1)),
                ('cuenta_x_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cxc_app.ctas_x_cobrar')),
            ],
            options={
                'db_table': 'cxc_det',
                'unique_together': {('cuenta_x_cobrar', 'fecha')},
            },
        ),
    ]
