# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conceptos_app', '0001_initial'),
        ('hecho_economico_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
        ('terceros_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAS_X_COBRAR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_cxc', models.CharField(max_length=10)),
                ('valor', models.FloatField(null=True)),
                ('fecha_des', models.DateField(blank=True, null=True)),
                ('fecha_exi', models.DateField(blank=True, null=True)),
                ('aplicado', models.CharField(choices=[('X', 'Por Causar'), ('A', 'Activo'), ('C', 'Cancelado'), ('T', 'Terminado Cupo'), ('D', 'Retirado con Deuda')], max_length=1)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptos_app.conceptos')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terceros_app.terceros')),
            ],
            options={
                'db_table': 'ctas_x_cobrar',
            },
        ),
        migrations.CreateModel(
            name='CXC_DET',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tip_mov', models.CharField(max_length=1)),
                ('valor', models.FloatField(null=True)),
                ('cuenta_x_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cxc_app.ctas_x_cobrar')),
                ('hecho_econo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hecho_economico_app.hecho_econo')),
            ],
            options={
                'db_table': 'cxc_det',
            },
        ),
        migrations.AddIndex(
            model_name='ctas_x_cobrar',
            index=models.Index(fields=['oficina', 'concepto'], name='ctas_x_cobr_oficina_fa1cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='ctas_x_cobrar',
            index=models.Index(fields=['oficina', 'tercero'], name='ctas_x_cobr_oficina_1f6474_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ctas_x_cobrar',
            unique_together={('oficina', 'cod_cxc')},
        ),
        migrations.AlterUniqueTogether(
            name='cxc_det',
            unique_together={('cuenta_x_cobrar', 'fecha')},
        ),
    ]
