# Generated by Django 4.2.4 on 2025-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas_app', '0001_initial'),
        ('cxc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ctas_x_cobrar',
            unique_together={('oficina', 'cod_cxc')},
        ),
        migrations.AddIndex(
            model_name='ctas_x_cobrar',
            index=models.Index(fields=['oficina', 'concepto'], name='ctas_x_cobr_oficina_fa1cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='ctas_x_cobrar',
            index=models.Index(fields=['oficina', 'tercero'], name='ctas_x_cobr_oficina_1f6474_idx'),
        ),
    ]
