# Generated by Django 4.2.4 on 2025-03-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0005_alter_terceros_unique_together_alter_terceros_id'),
        ('cxc_app', '0002_alter_ctas_x_cobrar_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctas_x_cobrar',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terceros_app.terceros'),
        ),
    ]
