# Generated by Django 4.2.4 on 2025-03-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos_app', '0001_initial'),
        ('cxc_app', '0003_alter_ctas_x_cobrar_tercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctas_x_cobrar',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptos_app.conceptos'),
        ),
    ]
