# Generated by Django 4.2.4 on 2025-03-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecho_economico_app', '0007_alter_hecho_econo_banco_alter_hecho_econo_ciudad_and_more'),
        ('cxc_app', '0004_alter_ctas_x_cobrar_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxc_det',
            name='hecho_econo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hecho_economico_app.hecho_econo'),
        ),
    ]
