# Generated by Django 4.2.4 on 2025-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc_app', '0005_cxc_det_hecho_econo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxc_det',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
