# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_producto_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREDITOS_CAUSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cre', models.CharField(max_length=10, null=True, verbose_name='Código Crédito')),
                ('cuota', models.IntegerField(default=0, verbose_name='Cuota')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('capital', models.FloatField(blank=True, null=True, verbose_name='Capital')),
                ('int_cor', models.FloatField(blank=True, null=True, verbose_name='Interés Corriente')),
                ('comprobante', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Comprobante')),
                ('oficina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'creditos_causa',
                'unique_together': {('oficina', 'cod_cre', 'comprobante', 'cuota')},
            },
        ),
    ]
