# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hecho_economico_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREDITOS_CAUSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cre', models.CharField(max_length=10, null=True, verbose_name='Código Crédito')),
                ('cuota', models.IntegerField(default=0, verbose_name='Cuota')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('capital', models.FloatField(blank=True, null=True, verbose_name='Capital')),
                ('int_cor', models.FloatField(blank=True, null=True, verbose_name='Interés Corriente')),
                ('comprobante', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hecho_economico_app.hecho_econo', verbose_name='Comprobante')),
                ('oficina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'creditos_causa',
                'indexes': [models.Index(fields=['oficina', 'cod_cre', 'comprobante'], name='creditos_ca_oficina_8a8802_idx')],
                'unique_together': {('oficina', 'cod_cre', 'comprobante', 'cuota')},
            },
        ),
    ]
