# Generated by Django 4.2.4 on 2024-09-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecho_economico_app', '0003_remove_hecho_econo_valor_hecho_econo_cheque_and_more'),
        ('causacion_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_causa',
            name='comprobante',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hecho_economico_app.hecho_econo', verbose_name='Comprobante'),
        ),
    ]
