# Generated by Django 4.2.4 on 2024-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causacion_creditos_app', '0002_alter_creditos_causa_comprobante'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditos_causa',
            index=models.Index(fields=['oficina', 'cod_cre', 'comprobante'], name='creditos_ca_oficina_8a8802_idx'),
        ),
    ]
