# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas_app', '0001_initial'),
        ('detalle_producto_app', '0001_initial'),
        ('hecho_economico_app', '0001_initial'),
        ('terceros_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLE_ECONO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_concepto', models.CharField(max_length=6, null=True, verbose_name='Item Concepto')),
                ('detalle', models.TextField(null=True, verbose_name='Detalle')),
                ('debito', models.FloatField(default=0, null=True, verbose_name='Valor Débito')),
                ('credito', models.FloatField(default=0, null=True, verbose_name='Valor Crédito')),
                ('valor_1', models.FloatField(default=0, null=True, verbose_name='Valor 1')),
                ('valor_2', models.FloatField(default=0, null=True, verbose_name='Valor 2')),
                ('id_ds', models.BigIntegerField(default=0, null=True, verbose_name='id_ds')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas_app.plan_ctas', verbose_name='Cuenta Contable')),
                ('detalle_prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Detalle Producto')),
                ('hecho_econo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hecho_economico_app.hecho_econo', verbose_name='Documento')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Tercero')),
            ],
            options={
                'db_table': 'detalle_econo',
                'indexes': [models.Index(fields=['hecho_econo', 'cuenta', 'tercero', 'detalle_prod'], name='detalle_eco_hecho_e_534ad7_idx'), models.Index(fields=['item_concepto'], name='detalle_eco_item_co_05e34f_idx')],
            },
        ),
    ]
