# Generated by Django 4.2.4 on 2024-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_economico_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detalle_econo',
            index=models.Index(fields=['item_concepto'], name='detalle_eco_item_co_05e34f_idx'),
        ),
    ]
