# Generated by Django 4.2.4 on 2025-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_economico_app', '0002_detalle_econo_detalle_eco_item_co_05e34f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_econo',
            name='credito',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Crédito'),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='debito',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Débito'),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='id_ds',
            field=models.BigIntegerField(default=0, null=True, verbose_name='id_ds'),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='valor_1',
            field=models.FloatField(default=0, null=True, verbose_name='Valor 1'),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='valor_2',
            field=models.FloatField(default=0, null=True, verbose_name='Valor 2'),
        ),
    ]
