# Generated by Django 4.2.4 on 2024-07-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociados_app', '0001_initial'),
        ('contabilizacion_capital_creditos_app', '0001_initial'),
        ('detalle_producto_app', '0001_initial'),
        ('lineas_credito_app', '0001_initial'),
        ('terceros_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREDITOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cre', models.CharField(max_length=10, null=True, verbose_name='Código Crédito')),
                ('libranza', models.CharField(max_length=10, null=True, verbose_name='Libranza')),
                ('pagare', models.CharField(max_length=16, null=True, verbose_name='Pagaré')),
                ('termino', models.CharField(choices=[('D', 'Definido'), ('C', 'Cupo'), ('R', 'Rotativo')], max_length=1, verbose_name='Término')),
                ('for_pag', models.CharField(choices=[('P', 'Personal'), ('L', 'Libranza'), ('T', 'Transferencia')], max_length=1, verbose_name='Forma de Pago')),
                ('tip_gar', models.CharField(choices=[('1', 'No Idónea'), ('2', 'Hipotecaria'), ('15', 'Sin Garantias')], default='15', max_length=2, verbose_name='Tipo de Garantía')),
                ('cap_ini', models.FloatField(blank=True, null=True, verbose_name='Capital Inicial')),
                ('fec_des', models.DateField(blank=True, null=True, verbose_name='Fecha Desembolso')),
                ('fec_pag_ini', models.DateField(blank=True, null=True, verbose_name='Fecha Pago Inicial')),
                ('fec_ree', models.DateField(blank=True, null=True, verbose_name='Fecha Reestructuración')),
                ('fec_ven', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fec_ult_pag', models.DateField(blank=True, null=True, verbose_name='Fecha Último Pago')),
                ('val_cuo_ini', models.FloatField(blank=True, null=True, verbose_name='Valor Cuota Incial')),
                ('val_cuo_act', models.FloatField(blank=True, null=True, verbose_name='Valor Cuota Actual')),
                ('num_cuo_ini', models.IntegerField(blank=True, null=True, verbose_name='Número Cuotas Iniciales')),
                ('num_cuo_act', models.IntegerField(blank=True, null=True, verbose_name='Número Cuotas Actuales')),
                ('num_cuo_gra', models.IntegerField(blank=True, null=True, verbose_name='Número Cuotas de Gracia')),
                ('per_ano', models.IntegerField(blank=True, null=True, verbose_name='Periodo')),
                ('tian_ic_ini', models.FloatField(blank=True, null=True, verbose_name='Interés Corriente Inicial')),
                ('tian_ic_act', models.FloatField(blank=True, null=True, verbose_name='Interés Corriente Actual')),
                ('tian_im', models.FloatField(blank=True, null=True, verbose_name='Interés Moratorio')),
                ('tian_pol_seg', models.FloatField(blank=True, null=True, verbose_name='Interés Póliza')),
                ('por_des_pro_pag', models.FloatField(blank=True, null=True, verbose_name='Descuento Pronto Pago')),
                ('decreciente', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Crédito Decreciente?')),
                ('estado', models.CharField(choices=[('X', 'Por Causar'), ('A', 'Activo'), ('C', 'Cancelado'), ('T', 'Terminado Cupo')], max_length=1, verbose_name='Estado')),
                ('est_jur', models.CharField(choices=[('N', 'Normal'), ('P', 'Persuasivo'), ('J', 'Cobro Jurídico'), ('C', 'Condonación'), ('T', 'Castigado')], max_length=1, verbose_name='Estado Jurídico')),
                ('cat_nue', models.CharField(choices=[('A', 'Normal'), ('B', 'Apreciable'), ('C', 'En Peligro'), ('D', 'En Mora'), ('E', 'Irrecuperable'), ('F', 'Castigado')], max_length=1, verbose_name='Categoria Incial')),
                ('rep_cen_rie', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Reportar a Centrales de Riesgos?')),
                ('val_gar_hip', models.FloatField(blank=True, null=True, verbose_name='Valor Garantía Hipotecaria')),
                ('mat_inm_gar', models.CharField(max_length=12, null=True, verbose_name='Número Matrícula Inmobiliaria')),
                ('num_pol_gar_hip', models.CharField(max_length=16, null=True, verbose_name='Número Póliza Garantia Hipotecaria')),
                ('figarantias', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Figarantías?')),
                ('cod_lin_cre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lineas_credito_app.lineas_credito', verbose_name='Línea de Crédito')),
                ('com_des', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Comprobante Desembolso')),
                ('imputacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilizacion_capital_creditos_app.imp_con_cre', verbose_name='Contabilización')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
                ('socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado')),
            ],
            options={
                'db_table': 'creditos',
                'unique_together': {('oficina', 'cod_cre')},
            },
        ),
        migrations.CreateModel(
            name='GAR_NO_IDONEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='C', max_length=1)),
                ('doc_ide', models.CharField(default='', max_length=12)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creditos_app.creditos')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas')),
            ],
            options={
                'db_table': 'gar_no_idonea',
                'unique_together': {('oficina', 'credito', 'doc_ide')},
            },
        ),
        migrations.CreateModel(
            name='CODEUDORES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creditos_app.creditos')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros')),
            ],
            options={
                'db_table': 'codeudores',
                'unique_together': {('oficina', 'credito', 'tercero')},
            },
        ),
    ]
