# Generated by Django 4.2.4 on 2024-08-24 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilizacion_capital_creditos_app', '0001_initial'),
        ('detalle_producto_app', '0001_initial'),
        ('asociados_app', '0001_initial'),
        ('lineas_credito_app', '0001_initial'),
        ('creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='cap_ini',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Capital Inicial'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='cat_nue',
            field=models.CharField(choices=[('A', 'Normal'), ('B', 'Apreciable'), ('C', 'En Peligro'), ('D', 'En Mora'), ('E', 'Irrecuperable'), ('F', 'Castigado')], default='A', max_length=1, verbose_name='Categoria Incial'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='cod_lin_cre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lineas_credito_app.lineas_credito', verbose_name='Línea de Crédito'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='com_des',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Comprobante Desembolso'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='decreciente',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Crédito Decreciente?'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='est_jur',
            field=models.CharField(choices=[('N', 'Normal'), ('P', 'Persuasivo'), ('J', 'Cobro Jurídico'), ('C', 'Condonación'), ('T', 'Castigado')], default='N', max_length=1, verbose_name='Estado Jurídico'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='estado',
            field=models.CharField(choices=[('X', 'Por Causar'), ('A', 'Activo'), ('C', 'Cancelado'), ('T', 'Terminado Cupo')], default='X', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='fec_des',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha Desembolso'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='figarantias',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Figarantías?'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='for_pag',
            field=models.CharField(choices=[('P', 'Personal'), ('L', 'Libranza'), ('T', 'Transferencia')], default='P', max_length=1, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='imputacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilizacion_capital_creditos_app.imp_con_cre', verbose_name='Imputacion Contable'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='libranza',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Libranza'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='mat_inm_gar',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='Número Matrícula Inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='num_cuo_act',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número Cuotas Actuales'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='num_cuo_gra',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número Cuotas de Gracia'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='num_cuo_ini',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número Cuotas Pactadas'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='num_pol_gar_hip',
            field=models.CharField(default=0, max_length=16, null=True, verbose_name='Número Póliza Garantia Hipotecaria'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='pagare',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Pagaré'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='per_ano',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Periodos por año'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='por_des_pro_pag',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Descuento Pronto Pago'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='rep_cen_rie',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='S', max_length=1, verbose_name='Reportar a Centrales de Riesgos?'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='socio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='termino',
            field=models.CharField(choices=[('D', 'Definido'), ('C', 'Cupo'), ('R', 'Rotativo')], default='D', max_length=1, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_ic_act',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tasa Int Cte Mensual Actual'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_ic_ini',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tasa Int Cte Mensual Pactado'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_im',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tasa Interés Moratorio'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='tian_pol_seg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tasa Interés Póliza'),
        ),
    ]
