# Generated by Django 4.2.4 on 2024-09-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0002_alter_creditos_cap_ini_alter_creditos_cat_nue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='fec_des',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Desembolso'),
        ),
    ]
