# Generated by Django 4.2.4 on 2024-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0005_alter_creditos_num_pol_gar_hip'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='porcentaje_prima',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Porcentaje Prima'),
        ),
        migrations.AddField(
            model_name='creditos',
            name='prima',
            field=models.CharField(choices=[('NO', 'No Tiene Extra prima'), ('PR', 'Prima'), ('EP', 'Extra Prima'), ('OP', 'Otra Prima')], default='NO', max_length=2, null=True, verbose_name='Primas?'),
        ),
    ]
