# Generated by Django 4.2.4 on 2024-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0006_creditos_porcentaje_prima_creditos_prima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='prima',
            field=models.CharField(choices=[('NO', 'No Tiene Extra prima'), ('PR', 'Prima'), ('EP', 'Extra Prima'), ('OP', 'Otra Prima')], default='NO', max_length=2, verbose_name='Primas?'),
        ),
    ]
