# Generated by Django 4.2.4 on 2024-12-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0007_alter_creditos_prima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos',
            name='num_pol_gar_hip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Número Garantia Hipotecaria'),
        ),
    ]
