# Generated by Django 4.2.4 on 2025-02-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0008_alter_creditos_num_pol_gar_hip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditos',
            index=models.Index(fields=['oficina', 'cod_cre'], name='creditos_oficina_5cf528_idx'),
        ),
    ]
