# Generated by Django 4.2.4 on 2025-03-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0009_creditos_creditos_oficina_5cf528_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='cod_des',
            field=models.CharField(default=' ', max_length=1, verbose_name='Destino Cre'),
        ),
    ]
