# Generated by Django 4.2.4 on 2025-03-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0010_creditos_cod_des'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditos',
            index=models.Index(fields=['oficina', 'socio'], name='creditos_oficina_0f05fa_idx'),
        ),
    ]
