# Generated by Django 4.2.4 on 2025-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0011_creditos_creditos_oficina_0f05fa_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='tiae_ic_ini',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tasa Efectiva Anual'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='per_ano',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Periodosa al Año'),
        ),
    ]
