# Generated by Django 4.2.4 on 2025-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_app', '0012_creditos_tiae_ic_ini_alter_creditos_per_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='tiae_ic_act',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tasa Efectiva Anual'),
        ),
    ]
