# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('localidades_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAGADORES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, null=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('pagador', models.CharField(max_length=72, null=True, verbose_name='Pagador')),
                ('tel_cel', models.CharField(max_length=10, null=True, verbose_name='Teléfono Celular')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='localidades_app.localidades', verbose_name='Ciudad')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'pagadores',
                'unique_together': {('cliente', 'codigo')},
            },
        ),
    ]
