# Generated by Django 5.2 on 2025-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagadores_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagadores',
            name='nit',
            field=models.CharField(max_length=10, null=True, verbose_name='Nit'),
        ),
    ]
