# Generated by Django 5.2 on 2025-07-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0005_rename_fec_ulp_pag_xmov_cre_fec_ult_pag_and_more'),
        ('pagadores_app', '0002_pagadores_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagadores',
            name='cliente',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pagadores',
            name='nit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nit'),
        ),
        migrations.AlterField(
            model_name='pagadores',
            name='pagador',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='pagadores',
            name='tel_cel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Celular'),
        ),
    ]
