# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades_app', '0001_initial'),
        ('terceros_app', '0001_initial'),
        ('pagadores_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASOCIADOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_aso', models.CharField(max_length=12, verbose_name='Código Asociado')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No Aplica')], max_length=1, verbose_name='Sexo')),
                ('est_civ', models.CharField(choices=[('N', 'No Aplica'), ('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('U', 'Unión Libre'), ('V', 'Viudo(a)'), ('E', 'Separado(a)'), ('D', 'Divorciado(a)')], max_length=1, verbose_name='Estado Civil')),
                ('fec_nac', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('zona', models.CharField(blank=True, max_length=16, null=True, verbose_name='Zona')),
                ('profesion', models.CharField(blank=True, max_length=48, null=True, verbose_name='Profesión')),
                ('ocupacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ocupación')),
                ('ocupacion_cod', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código Ocupación')),
                ('estrato', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estrato')),
                ('niv_est', models.CharField(choices=[('0', 'No Aplica'), ('1', 'Primaria'), ('2', 'Bachiller'), ('3', 'Técnico'), ('4', 'Tecnólogo'), ('5', 'Profesional'), ('6', 'PosGrado'), ('7', 'Maestria'), ('8', 'Doctorado'), ('9', 'Otros')], max_length=1, verbose_name='Nivel de Estudio')),
                ('cab_fam', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cabeza de Familia?')),
                ('fec_afi', models.DateField(blank=True, null=True, verbose_name='Fecha Afiliación')),
                ('cargo_emp', models.CharField(max_length=36, null=True, verbose_name='Cargo en la Empresa')),
                ('per_a_cargo', models.IntegerField(blank=True, null=True, verbose_name='Personas a Cargo')),
                ('num_hij_men', models.IntegerField(blank=True, null=True, verbose_name='Número Hijos Menores')),
                ('num_hij_may', models.IntegerField(blank=True, null=True, verbose_name='Número Hijos Mayores')),
                ('tip_viv', models.CharField(max_length=24, null=True, verbose_name='Tipo de Vivienda')),
                ('tie_en_ciu', models.IntegerField(blank=True, null=True, verbose_name='Tiempo en la Ciudad')),
                ('med_con', models.CharField(max_length=48, null=True, verbose_name='med_con')),
                ('fec_ing_tra', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso Trabajo')),
                ('tel_tra', models.CharField(max_length=10, null=True, verbose_name='Teléfono Trabajo')),
                ('tip_sal', models.CharField(max_length=18, null=True, verbose_name='Tipo de Salario')),
                ('act_eco', models.CharField(max_length=24, null=True, verbose_name='Actividad Económica')),
                ('cod_ciiu', models.CharField(max_length=12, null=True, verbose_name='Código CIIU')),
                ('tip_con', models.CharField(max_length=18, null=True, verbose_name='Tipo Contrato')),
                ('nom_emp', models.CharField(max_length=40, null=True, verbose_name='Nombre Empresa')),
                ('nit_emp', models.CharField(max_length=12, null=True, verbose_name='Nit Empresa')),
                ('dir_emp', models.CharField(max_length=50, null=True, verbose_name='Dirección Empresa')),
                ('email_emp', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail Empresa')),
                ('sector_emp', models.CharField(max_length=12, null=True, verbose_name='Sector Empresa')),
                ('empresa_ant', models.IntegerField(blank=True, null=True, verbose_name='Empresa Anterior')),
                ('emp_num_emp', models.IntegerField(blank=True, null=True, verbose_name='Numero Empleados')),
                ('negocio_pro', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Negocio Propio?')),
                ('negocio_nom', models.CharField(max_length=48, null=True, verbose_name='Nombre Negocio')),
                ('negocio_tel', models.CharField(max_length=10, null=True, verbose_name='Teléfono Negocio')),
                ('negocio_loc_pro', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Local Propio?')),
                ('negocio_cam_com', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tiene Cámara Comercio?')),
                ('negocio_ant', models.IntegerField(blank=True, null=True, verbose_name='Antiguedad Negocio')),
                ('pension_ent', models.CharField(max_length=36, null=True, verbose_name='Entidad de Pensión')),
                ('pension_tie', models.IntegerField(blank=True, null=True, verbose_name='Tiene Pension')),
                ('pension_otr', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Otra Pensión?')),
                ('pension_ent_otr', models.CharField(max_length=36, null=True, verbose_name='Entidad Otra Pensión')),
                ('pep_es_fam', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tiene Familiar PEP?')),
                ('pep_fam_par', models.CharField(choices=[('0', 'No Aplica'), ('1', 'Esposo(a)'), ('2', 'Hijo(a)'), ('3', 'Padre o Madre'), ('4', 'Abuelo(a)'), ('5', 'Nieto(a)'), ('6', 'Hermano'), ('7', 'Hermana'), ('8', 'Primo(a)'), ('9', 'Otro Familiar')], max_length=1, verbose_name='Parentesco Familiar PEP')),
                ('pep_fam_nom', models.CharField(max_length=36, null=True, verbose_name='Nombre Familiar PEP')),
                ('pep_car_pub', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tiene Cargo Público PEP?')),
                ('pep_cargo', models.CharField(max_length=36, null=True, verbose_name='Cargo PEP')),
                ('pep_eje_pod', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='PEP Eje Pod?')),
                ('pep_adm_rec_est', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Administra Recursos del Estado PEP?')),
                ('tie_gre_car', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tiene Gre Car?')),
                ('recibe_pag_ext', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Recibe Pagos del Extranjero?')),
                ('recide_ext_mas_186', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Recibe Extranjero +186?')),
                ('recibe_ing_ext', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Recibe Ingresos Extranjeros?')),
                ('estado_anteia', models.CharField(choices=[('0', 'No Anteia'), ('1', 'Validar'), ('2', 'Por Validar'), ('3', 'Denegar')], default=2, max_length=1, verbose_name='Estado Anteia')),
                ('ciu_tra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_tra', to='localidades_app.localidades', verbose_name='Ciudad de Trabajo')),
                ('id_pag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagadores_app.pagadores', verbose_name='Empresa Nominadora')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
                ('tercero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Tercero')),
            ],
            options={
                'db_table': 'asociados',
                'unique_together': {('oficina', 'cod_aso')},
            },
        ),
        migrations.CreateModel(
            name='ASO_REFERENCIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ref', models.CharField(choices=[('0', 'No Aplica'), ('1', 'Familiar'), ('2', 'Personal'), ('3', 'Bancaria'), ('4', 'Comercial'), ('5', 'Laboral')], max_length=1, verbose_name='Tipo Referencia')),
                ('parentesco', models.CharField(choices=[('0', 'No Aplica'), ('1', 'Esposo(a)'), ('2', 'Hijo(a)'), ('3', 'Padre o Madre'), ('4', 'Abuelo(a)'), ('5', 'Nieto(a)'), ('6', 'Hermano'), ('7', 'Hermana'), ('8', 'Primo(a)'), ('9', 'Otro Familiar')], max_length=1, verbose_name='Parentesco')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre Completo')),
                ('ocupacion', models.CharField(max_length=32, verbose_name='Ocupación')),
                ('empresa', models.CharField(max_length=40, verbose_name='Empresa')),
                ('direccion', models.CharField(max_length=64, verbose_name='Dirección')),
                ('tel_fijo', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('tel_cel', models.CharField(max_length=10, verbose_name='Celular')),
                ('tel_emp', models.CharField(max_length=10, verbose_name='Teléfono Empresa')),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado')),
            ],
            options={
                'db_table': 'aso_referencias',
                'unique_together': {('asociado', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ASO_BENEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_doc', models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('T', 'Tarjeta de Identidad'), ('N', 'Nit'), ('R', 'Registro Civil'), ('E', 'Cédula de Extranjería'), ('P', 'Pasaporte'), ('O', 'Otros')], max_length=1, verbose_name='Clase Documento')),
                ('doc_ide', models.CharField(max_length=12, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre Completo')),
                ('agno_nac', models.IntegerField(blank=True, null=True, verbose_name='Año de Nacimiento')),
                ('parentesco', models.CharField(choices=[('0', 'No Aplica'), ('1', 'Esposo(a)'), ('2', 'Hijo(a)'), ('3', 'Padre o Madre'), ('4', 'Abuelo(a)'), ('5', 'Nieto(a)'), ('6', 'Hermano'), ('7', 'Hermana'), ('8', 'Primo(a)'), ('9', 'Otro Familiar')], max_length=1, verbose_name='Parentesco')),
                ('porcentaje', models.FloatField(blank=True, null=True, verbose_name='Porcentaje')),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado')),
            ],
            options={
                'db_table': 'aso_benef',
                'unique_together': {('asociado', 'doc_ide')},
            },
        ),
    ]
