# Generated by Django 5.2 on 2025-06-15 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0001_initial'),
        ('ciiu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aso_referencias',
            name='es_fam_dir_cli',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Es familiar de un directivo Entidad'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='barrio_aso',
            field=models.CharField(max_length=40, null=True, verbose_name='barrio asociado'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono Conyuge'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_ciudad',
            field=models.CharField(blank=True, max_length=24, verbose_name='conyuge Trabaja?'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_dir_empresa',
            field=models.CharField(max_length=50, null=True, verbose_name='Empresa Conyuge'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_doc_ide',
            field=models.CharField(max_length=12, null=True, verbose_name='Doc_ide Conyuge'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_empresa',
            field=models.CharField(max_length=50, null=True, verbose_name='Empresa Conyuge'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_fec_ing_emp',
            field=models.CharField(max_length=4, null=True, verbose_name='agno ing empresas'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_ingresos',
            field=models.FloatField(blank=True, null=True, verbose_name='Ingresos por Honoarios'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_nombre',
            field=models.CharField(max_length=36, null=True, verbose_name='Nombre Conyuge'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_ocupacion',
            field=models.CharField(max_length=30, null=True, verbose_name='Ocupacion Conyuge'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_telefono',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefono Conyuge'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='conyuge_trabaja',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='conyuge Trabaja?'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='emp_ent',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Empleado de COORINOQUIA?'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Ingresó Nuevamente'), ('S', 'Suspendido'), ('Z', 'Retirado con Crédito'), ('R', 'Retirado'), ('F', 'Fallecido')], default='A', max_length=1, verbose_name='Estado en la Entidad'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='fec_ret',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Retiro'),
        ),
        migrations.AddField(
            model_name='asociados',
            name='negocio_pro_local',
            field=models.CharField(max_length=40, null=True, verbose_name='agno ing empresas'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='act_eco',
            field=models.CharField(choices=[('1', 'Intermediacion Financiera'), ('2', 'Servicios de Ahorro y Credito'), ('3', 'Organismos de Representacion'), ('4', 'Agricola'), ('5', 'Pecuaria'), ('6', 'Silvicultura'), ('7', 'Pesca'), ('8', 'Mineria'), ('9', 'Educacion'), ('10', 'Transporte'), ('11', 'Vivienda'), ('12', 'Consumo (Comercio)'), ('13', 'Industria'), ('14', 'Servicios Funerarios'), ('15', 'Comunicaciones'), ('16', 'Obras Publicas'), ('17', 'Hoteles Restaurantes Bares'), ('18', 'Turismo'), ('19', 'Aseo Mantenimiento Reciclaje'), ('20', 'Inmobiliarias y de Alquiler'), ('21', 'Seguros'), ('22', 'Salud'), ('23', 'Vigilancia y seguridad'), ('24', 'Servicios de Credito'), ('99', 'Otras Actividades')], max_length=2, null=True, verbose_name='Actividad Económica'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='cod_ciiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ciiu_app.ciiu', verbose_name='Código CIIU'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='estado_anteia',
            field=models.CharField(choices=[('0', 'No Anteia'), ('1', 'Validar'), ('2', 'Validado'), ('3', 'Denegar')], default=2, max_length=1, verbose_name='Estado Anteia'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='estrato',
            field=models.CharField(choices=[('N', 'No Aplica'), ('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco'), ('6', 'Seis')], max_length=1, verbose_name='Estrato'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='fec_ing_tra',
            field=models.DateField(null=True, verbose_name='Fecha Ingreso Trabajo'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='fec_nac',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='med_con',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='med_con'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_cam_com',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Tiene Cámara Comercio?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_loc_pro',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Local Propio?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_nom',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Nombre Negocio'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_pro',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Negocio Propio?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_tel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Negocio'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='num_hij_may',
            field=models.IntegerField(default='0', null=True, verbose_name='Número Hijos Mayores'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='num_hij_men',
            field=models.IntegerField(default='0', null=True, verbose_name='Número Hijos Menores'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='ocupacion',
            field=models.CharField(choices=[('0', 'No aplica'), ('1', 'Empleado'), ('2', 'Independiente'), ('3', 'Pensionado'), ('4', 'Estudiante'), ('5', 'Hogar'), ('6', 'Cesante'), ('7', 'Menor de Edad'), ('8', 'Empleado Término Fijo'), ('9', 'Empleado Temporal'), ('A', 'Entidad Sin Ánimo de Lucro')], max_length=1, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_ent_otr',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Entidad Otra Pensión'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_otr',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Otra Pensión?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_adm_rec_est',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Administra Recursos del Estado PEP?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_car_pub',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Tiene Cargo Público PEP?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_cargo',
            field=models.CharField(default='N', max_length=36, null=True, verbose_name='Cargo PEP'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_eje_pod',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='PEP Eje Pod?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_es_fam',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Tiene Familiar PEP?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_fam_nom',
            field=models.CharField(default='N', max_length=36, null=True, verbose_name='Nombre Familiar PEP'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_fam_par',
            field=models.CharField(blank=True, choices=[('0', 'No Aplica'), ('1', 'Esposo(a)'), ('2', 'Hijo(a)'), ('3', 'Padre o Madre'), ('4', 'Abuelo(a)'), ('5', 'Nieto(a)'), ('6', 'Hermano'), ('7', 'Hermana'), ('8', 'Primo(a)'), ('9', 'Otro Familiar')], max_length=1, verbose_name='Parentesco Familiar PEP'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='per_a_cargo',
            field=models.IntegerField(default='0', null=True, verbose_name='Personas a Cargo'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='recibe_ing_ext',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Recibe Ingresos Extranjeros?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='recibe_pag_ext',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Recibe Pagos del Extranjero?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='recide_ext_mas_186',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Recibe Extranjero +186?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tel_tra',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Trabajo'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tie_gre_car',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Tiene Gre Car?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tip_con',
            field=models.CharField(blank=True, choices=[('0', 'No Aplica'), ('1', 'No Empleado'), ('2', 'Término Indefinido'), ('3', 'Término Fijo Mayor a 1 Año'), ('4', 'Término Fijo Menor a 1 Año'), ('5', 'Culmincación de Obra'), ('6', 'Por Cooperativa'), ('7', 'Orden de Prestación de Servicios'), ('8', 'Otros')], max_length=18, null=True, verbose_name='Tipo Contrato'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tip_sal',
            field=models.CharField(choices=[('0', 'No Aplica'), ('1', 'Convencional'), ('2', 'Integral'), ('3', 'Por Obra'), ('4', 'Jornal'), ('5', 'Variable'), ('6', 'Otros')], max_length=1, null=True, verbose_name='Tipo de Salario'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tip_viv',
            field=models.CharField(choices=[('P', 'Propia'), ('F', 'Familiar'), ('A', 'Arrendada')], max_length=1, verbose_name='Tipo de Vivienda'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='zona',
            field=models.CharField(choices=[('U', 'Urbana'), ('R', 'Rural')], default='U', max_length=1, verbose_name='Zona'),
        ),
    ]
