# Generated by Django 5.2 on 2025-07-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0002_aso_referencias_es_fam_dir_cli_asociados_barrio_aso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='cod_ent',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Entidad Pagadora'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_nom',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Actividad Económica DANE'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_tie',
            field=models.CharField(choices=[('1', 'Vejez'), ('2', 'Invalidez'), ('3', 'Sobrevivientes'), ('4', 'Sustitución'), ('5', 'Menores de Edad'), ('6', 'Asignación de Retiro')], default='N', max_length=1, verbose_name='Tipo Pensión?'),
        ),
    ]
