# Generated by Django 4.2.4 on 2024-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0002_aso_referencias_es_fam_dir_cli_asociados_barrio_aso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Ingreso Nuevamente'), ('S', 'Suspendido'), ('Z', 'Retirado con Credito'), ('R', 'Retirado'), ('F', 'Fallecido')], max_length=1, verbose_name='Estado en la Entidad'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='estado_anteia',
            field=models.CharField(choices=[('0', 'No Anteia'), ('1', 'Validar'), ('2', 'Validado'), ('3', 'Denegar')], default=2, max_length=1, verbose_name='Estado Anteia'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='med_con',
            field=models.CharField(max_length=100, null=True, verbose_name='med_con'),
        ),
    ]
