# Generated by Django 5.2 on 2025-07-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0003_asociados_cod_ent_alter_asociados_negocio_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociados',
            name='cod_ent',
        ),
    ]
