# Generated by Django 4.2.4 on 2025-02-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0003_asociados_estado_alter_asociados_estado_anteia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='emp_ent',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Empleado de la Entidad?'),
        ),
    ]
