# Generated by Django 4.2.4 on 2025-02-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0004_asociados_emp_ent'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='fec_ret',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Afiliación'),
        ),
    ]
