# Generated by Django 5.2 on 2025-07-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0004_remove_asociados_cod_ent'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='asociados',
        #    name='pension_tip',
        #    field=models.CharField(choices=[('1', 'Vejez'), ('2', 'Invalidez'), ('3', 'Sobrevivientes'), ('4', 'Sustitución'), ('5', 'Menores de Edad'), ('6', 'Asignación de Retiro')], default='N', max_length=1, verbose_name='Tipo Pensión?'),
        #),
        #migrations.AlterField(
        #    model_name='asociados',
        #    name='negocio_nom',
        #    field=models.CharField(blank=True, choices=[('1', 'Agricultura, ganadería, caza, silvicultura y pesca'), ('2', 'Explotación de minas y canteras'), ('3', 'Industrias manufactureras'), ('4', 'Construcción'), ('5', 'Suministro de servicios públicos'), ('6', 'Comercio al por mayor y al por menor; Reparación de vehículos; Transporte y almacenamiento; Alojamiento y servicios de comida'), ('7', 'Información y comunicaciones'), ('8', 'Actividades financieras y de seguros'), ('9', 'Actividades inmobiliarias'), ('10', 'Actividades profesionales, científicas y técnicas; Actividades de servicios administrativos y de apoyo'), ('11', 'Administración pública y defensa; planes de seguridad social; Educación; Actividades de salud humana y servicios sociales'), ('12', 'Actividades artísticas, recreación y de servicios; Actividades de los hogares (empleadores); Actividades no diferenciadas de los hogares')], max_length=2, null=True, verbose_name='Actividad Económica DANE'),
        #),
        migrations.AlterField(
            model_name='asociados',
            name='pension_tie',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Tiene Pensión?'),
        ),
    ]
