# Generated by Django 5.2 on 2025-07-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0005_asociados_pension_tip_alter_asociados_negocio_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='negocio_nom',
            field=models.CharField(blank=True, choices=[('1', 'Agricultura, ganadería, caza, silvicultura y pesca'), ('2', 'Explotación de minas y canteras'), ('3', 'Industrias manufactureras'), ('4', 'Construcción'), ('5', 'Suministro de servicios públicos'), ('6', 'Comercio al por mayor y al por menor; Reparación de vehículos; Transporte y almacenamiento; Alojamiento y servicios de comida'), ('7', 'Información y comunicaciones'), ('8', 'Actividades financieras y de seguros'), ('9', 'Actividades inmobiliarias'), ('10', 'Actividades profesionales, científicas y técnicas; Actividades de servicios administrativos y de apoyo'), ('11', 'Administración pública y defensa; planes de seguridad social; Educación; Actividades de salud humana y servicios sociales'), ('12', 'Actividades artísticas, recreación y de servicios; Actividades de los hogares (empleadores); Actividades no diferenciadas de los hogares')], max_length=48, null=True, verbose_name='Actividad Económica DANE'),
        ),
    ]
