# Generated by Django 4.2.4 on 2025-03-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0005_asociados_fec_ret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Ingresó Nuevamente'), ('S', 'Suspendido'), ('Z', 'Retirado con Crédito'), ('R', 'Retirado'), ('F', 'Fallecido')], max_length=1, verbose_name='Estado en la Entidad'),
        ),
    ]
