# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOV_CAJA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('cod_caj', models.CharField(max_length=2, verbose_name='Código Cajero')),
                ('jornada', models.CharField(max_length=1, verbose_name='Jornada')),
                ('saldo_ini', models.FloatField(blank=True, null=True, verbose_name='Saldo Inicial')),
                ('debitos', models.FloatField(blank=True, null=True, verbose_name='Movimientos Débitos')),
                ('creditos', models.FloatField(blank=True, null=True, verbose_name='Movimientos Créditos')),
                ('val_che_dev', models.FloatField(blank=True, null=True, verbose_name='Valor Cheques Devueltos')),
                ('saldo_fin', models.FloatField(blank=True, null=True, verbose_name='Saldo Final')),
                ('diferencia', models.FloatField(blank=True, null=True, verbose_name='Diferencia')),
                ('val_cheques', models.FloatField(blank=True, null=True, verbose_name='Valor Cheques')),
                ('val_vales', models.FloatField(blank=True, null=True, verbose_name='Valor Vales')),
                ('cerrado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cierre de Caja?')),
                ('monedas', models.JSONField(blank=True, null=True, verbose_name='Dinero en Efectivo')),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'mov_caja',
                'unique_together': {('oficina', 'fecha', 'cod_caj', 'jornada')},
            },
        ),
    ]
