# Generated by Django 4.2.4 on 2024-10-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajeros_app', '0001_initial'),
        ('movimiento_caja_app', '0002_mov_caja_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mov_caja',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mov_caja',
            name='cajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cajeros_app.cajeros', verbose_name='Cajero'),
        ),
        migrations.AlterUniqueTogether(
            name='mov_caja',
            unique_together={('cajero', 'fecha', 'jornada')},
        ),
        migrations.RemoveField(
            model_name='mov_caja',
            name='cod_caj',
        ),
        migrations.RemoveField(
            model_name='mov_caja',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='mov_caja',
            name='user',
        ),
    ]
