# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLAN_CTAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_con', models.IntegerField(blank=True, null=True, verbose_name='Periodo Contable')),
                ('cod_cta', models.CharField(max_length=10, null=True, verbose_name='Código Cuenta')),
                ('nom_cta', models.CharField(max_length=64, null=True, verbose_name='Nombre Cuenta')),
                ('tip_cta', models.CharField(choices=[('C', 'Cuenta'), ('A', 'Auxiliar')], max_length=1, null=True, verbose_name='Tipo Cuenta')),
                ('dinamica', models.TextField(blank=True, verbose_name='Dinámica')),
                ('naturaleza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='Naturaleza')),
                ('activa', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Activa?')),
                ('por_tercero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Contabiliza por Tercero?')),
                ('cta_act_fij', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Activo Fijo?')),
                ('cta_pre', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Presupuesto?')),
                ('cta_bal', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta de Balance?')),
                ('cta_res', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta de Resultados?')),
                ('cta_ord', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta de Orden?')),
                ('cta_ban', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta de Banco?')),
                ('cta_gan_per', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Ganancias?')),
                ('cta_per_gan', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Pérdidas?')),
                ('cta_dep', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Depreciación?')),
                ('cta_ing_ret', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Ingresos y Retenciones?')),
                ('cta_ret_iva', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Reteiva?')),
                ('cta_rec', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Cuenta Recíproca?')),
                ('id_ds', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'plan_ctas',
                'unique_together': {('cliente', 'per_con', 'cod_cta')},
            },
        ),
    ]
