# Generated by Django 4.2.4 on 2024-06-20 20:33

from django.db import migrations, models
import justo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, verbose_name='Código')),
                ('doc_ide', models.CharField(help_text='El documento de identidad debe ser numérico.', max_length=12, validators=[justo_app.models.validate_numeric], verbose_name='Nit')),
                ('dv', models.CharField(blank=True, max_length=1, null=True, verbose_name='DV')),
                ('sigla', models.CharField(max_length=36, verbose_name='Sigla')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('clase_coop', models.CharField(choices=[('AS', 'Asociaciones Mutuales'), ('TA', 'Trabajo Asociado'), ('EAYC', 'Especializada de Ahorro Y Crédito'), ('ESSA', 'Especializada sin Sección de Ahorros'), ('FE', 'Fondo de Empleados'), ('ISSA', 'Integral Sin Sección de Ahorros'), ('MASSA', 'Multi Activa Sin Sección de Ahorros')], default='EAYC', max_length=8, verbose_name='Clase Cooperativa')),
                ('direccion', models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, help_text='El número de teléfono debe tener solo dígitos numéricos.', max_length=12, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Teléfono')),
                ('celular', models.CharField(help_text='El número de celular debe contener exactamente 10 dígitos numéricos.', max_length=10, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Celular')),
                ('ciudad', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ciudad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('dominio', models.URLField(verbose_name='Dominio')),
                ('nit_ger', models.CharField(blank=True, help_text='El número de documento debe ser numérico.', max_length=10, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Documento Gerente')),
                ('nom_ger', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Gerente')),
                ('nit_con', models.CharField(blank=True, help_text='El número de documento debe ser numérico.', max_length=10, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Documento Contador')),
                ('nom_con', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contador')),
                ('tp_con', models.CharField(blank=True, max_length=16, null=True, verbose_name='Tar. Prof. Contador')),
                ('nit_rev_fis', models.CharField(blank=True, help_text='El número de documento debe ser numérico.', max_length=10, null=True, validators=[justo_app.models.validate_numeric], verbose_name='Documento Revisor Fiscal')),
                ('nom_rev_fis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Revisor Fiscal')),
                ('tp_rev_fis', models.CharField(blank=True, max_length=16, null=True, verbose_name='Tar. Prof. Revisor')),
                ('age_ret', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Agente Retención')),
                ('ret_iva', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Retiene Iva')),
                ('aut_ret', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Autorretenedor')),
                ('logo', models.FileField(blank=True, max_length=254, null=True, upload_to='', verbose_name='Logo')),
                ('num_lic', models.CharField(max_length=8, verbose_name='Número Licencia')),
                ('lic_act', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Licencia Activa')),
                ('ini_lic', models.DateField(verbose_name='Fecha Incio Licencia')),
                ('fin_lic', models.DateField(verbose_name='Fecha Fin Licencia')),
            ],
            options={
                'db_table': 'clientes',
                'unique_together': {('codigo',)},
            },
        ),
    ]
