# Generated by Django 4.2.4 on 2024-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMOV_CRE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_cre', models.CharField(max_length=10)),
                ('est_jur', models.CharField(max_length=1)),
                ('fec_ulp_pag', models.DateField(null=True)),
                ('min_fecha', models.DateField(null=True)),
                ('max_fecha', models.DateField(null=True)),
                ('clase', models.CharField(max_length=1)),
                ('docto', models.CharField(max_length=10)),
                ('tip_mov', models.CharField(max_length=1)),
                ('fecha', models.DateField(null=True)),
                ('capital', models.FloatField(null=True)),
                ('int_cor', models.FloatField(null=True)),
                ('int_mor', models.FloatField(null=True)),
                ('acreed', models.FloatField(null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'xmov_cre',
                'indexes': [models.Index(fields=['tip_mov'], name='xmov_cre_tip_mov_518647_idx')],
            },
        ),
    ]
