# Generated by Django 4.2.4 on 2024-06-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_xmov_cre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='clase_coop',
            field=models.CharField(choices=[('AS', 'Asociaciones Mutuales'), ('TA', 'Trabajo Asociado'), ('EAYC', 'Especializada de Ahorro Y Credito'), ('ESSA', 'Especializada sin Seccion de Ahorro'), ('FE', 'Fondo de Empleados'), ('ISSA', 'Integral Sin Seccion de Ahorro'), ('MASSA', 'Multi Activa Sin Seccion de Ahorros')], default='EAYC', max_length=8, verbose_name='Clase Cooperativa'),
        ),
    ]
