# Generated by Django 4.2.4 on 2024-11-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0003_alter_clientes_clase_coop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fin_lic',
            field=models.DateField(null=True, verbose_name='Fecha Fin Licencia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ini_lic',
            field=models.DateField(null=True, verbose_name='Fecha Incio Licencia'),
        ),
    ]
