# Generated by Django 4.2.4 on 2024-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0004_alter_clientes_fin_lic_alter_clientes_ini_lic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmov_cre',
            old_name='fec_ulp_pag',
            new_name='fec_ult_pag',
        ),
        migrations.AddField(
            model_name='xmov_cre',
            name='fecdes',
            field=models.DateField(null=True),
        ),
    ]
