# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLAN_APORTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agno', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('meses', models.IntegerField(blank=True, null=True, verbose_name='Meses')),
                ('iniadu', models.FloatField(blank=True, null=True, verbose_name='IniAdu')),
                ('totadu', models.FloatField(blank=True, null=True, verbose_name='TotAdu')),
                ('inichi1', models.FloatField(blank=True, null=True, verbose_name='IniChi1')),
                ('totchi1', models.FloatField(blank=True, null=True, verbose_name='TotChi1')),
                ('inichi2', models.FloatField(blank=True, null=True, verbose_name='IniChi2')),
                ('totchi2', models.FloatField(blank=True, null=True, verbose_name='TotChi2')),
                ('inijur', models.FloatField(blank=True, null=True, verbose_name='IniJur')),
                ('totjur', models.FloatField(blank=True, null=True, verbose_name='TotJur')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'plan_aportes',
                'unique_together': {('oficina', 'agno')},
            },
        ),
    ]
