# Generated by Django 5.2.13 on 2026-06-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMP_CON_CRE_INT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_imp', models.CharField(max_length=2, null=True, verbose_name='Código')),
                ('categoria', models.CharField(choices=[('A', 'Normal'), ('B', 'Apreciable'), ('C', 'En Peligro'), ('D', 'En Mora'), ('E', 'Irrecuperable'), ('F', 'Castigado')], max_length=1, verbose_name='Categoria')),
                ('kcta_con', models.CharField(max_length=10, null=True, verbose_name='Cuenta Contable')),
                ('kcta_pro_ind', models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Individual')),
                ('cta_pro_ind_cap', models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Ind Kapital')),
                ('cta_pro_ind_int', models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Ind Interes')),
                ('kporcentaje', models.FloatField(blank=True, null=True, verbose_name='Porcentaje')),
                ('cta_int', models.CharField(max_length=10, null=True, verbose_name='Cuenta Intereses')),
                ('cta_ord_int', models.CharField(max_length=10, null=True, verbose_name='Cuenta de Orden Intereses')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'imp_con_cre_int',
                'unique_together': {('cliente', 'cod_imp', 'categoria')},
            },
        ),
    ]
