# Generated by Django 4.2.4 on 2025-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilizacion_intereses_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_con_cre_int',
            name='cta_pro_ind_cap',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Ind Kapital'),
        ),
        migrations.AddField(
            model_name='imp_con_cre_int',
            name='cta_pro_ind_int',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Ind Interes'),
        ),
    ]
